### ISSUE TITLE
Wiki Changes

### ISSUE THREAD

**Issue by DragonDev15** [brainboxdotcc/DPP#10]
Thank me l8r.

https://gist.github.com/DragonDev15/a6a1ad27dab87c1aa6f922c6c25fe205

**Comment by webtax-gh** [comment]
I'm sort of confused by this issue.

Have you already made these changes to the wiki? Do you have permission to change the wiki?

If you don't have perms to edit the wiki, ping me and I can do it for you, otherwise you can just change the wiki without making a PR.

**Comment by braindigitalis** [comment]
Dragon doesnt have access to change the wiki,.
Sending a PR for a wiki is a convoluted process so i said for him to just send us a git diff of his changes from a clone of the wiki and we can merge it in.

**Comment by braindigitalis** [comment]
i've merged this into the new wiki, new wiki pages can be found in the standard repository under the `docpages` folder. 

You can build a copy of the documentation by running doxygen from the top level folder of the source tree.

The new site and documentation are here:

https://dpp.brainbox.cc/

**Comment by braindigitalis** [comment]
#
