### ISSUE TITLE
xmake dpp.lib(cluster.cpp.obj) : error LNK2019

### ISSUE THREAD

**Issue by FabriicioMelo** [brainboxdotcc/DPP#1007]
**Git commit reference:**
ffa2653f7504a701735ed23cfb2d503648253a96

**Describe the bug:**
When trying to install dpp through xmake, I receive this error, which does not allow me to start the project.

**To Reproduce:**
1. Create a new xmake project
2. Update the xmake.lua file by adding the dpp package, below the minimum configuration:
```
add_rules("mode.debug", "mode.release")

add_requires("dpp")

target("test-bot")
	set_kind("binary")
	add_files("src/*.cpp")

	add_packages("dpp")
``` 
5. Then build it `xmake build`

**Screenshots:**
![image](https://github.com/brainboxdotcc/DPP/assets/96056721/cbb80931-ec1f-4927-9f5f-d8ce0b64b33f)

**System Details:**
 - OS: Windows 11 Pro 64 bits 
 - Version: 22621.2715

**Adicional Info:**
I literally did what I was told on your website, here is the link: [https://dpp.dev/10.0.28/install-xmake.html](url)

**Comment by Jaskowicz1** [comment]
@Mishura4 This is related to #980. Is this because it's not ran inside visual studio?

**Comment by Mishura4** [comment]
I'll investigate. In the meantime you can add `DPP_BYPASS_VERSION_CHECKING` to the list of defines in your project to work around this

**Comment by braindigitalis** [comment]
you didn't link the windows sdk which contains the messageboxA function, this is required client side in the program which includes dpp.

**Comment by FabriicioMelo** [comment]
@braindigitalis Thanks to you, I managed to compile. I found how to link to the sdk.
My xmake.lua file now looks like this:
```
add_rules("mode.debug", "mode.release")

add_requires("dpp")

target("test-bot")
    add_rules("win.sdk.application")

    set_kind("binary")
    add_files("src/*.cpp")

    add_packages("dpp")
``` 
You need to update this on your website.

**Comment by Mishura4** [comment]
Please don't close this if it's not yet resolved on our end.

Thank you though for the solution, we'll look at this. There are potentially other solutions as well.

**Comment by Jaskowicz1** [comment]
Maybe we could simply change the solution to fix this? If the windows api is found (check with `#ifdef`) then we do the message box, otherwise we could do a fallback and just send the error log via `std::cout` or something.

**Comment by Mishura4** [comment]
I have ideas, I'll take a look soon
Very busy atm so probably next week

**Comment by Jaskowicz1** [comment]
> I have ideas, I'll take a look soon Very busy atm so probably next week

Okie dokie!

**Comment by Mishura4** [comment]
![i forgor](https://media.discordapp.net/stickers/1090754461695225886.webp?size=160)

**Comment by braindigitalis** [comment]
did you forgor mor?

**Comment by Jaskowicz1** [comment]
@Mishura4 Did you forgor even mor?

**Comment by Nk125** [comment]
Why not including the pure user32.lib from windows?, I'm not so experienced handling with xmake but something like a pragma to import user32 in [this lines](https://github.com/brainboxdotcc/DPP/blob/c42b42cfe8ae9e8ac2c0bd4cd5056818c39cb245/src/dpp/cluster.cpp#L71-L83).
Also would be useful if `TEXT()` macro ([defined in windows.h](https://learn.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-text)) is used in MessageBox to support unicode and non-unicode windows builds, avoiding compile issues in the future.

```cpp
#ifdef _WIN32
#include <windows.h>
#pragma comment(lib, "user32.lib")

if constexpr (BuildType != build_type::universal && BuildType != expected) {
		MessageBox(
			nullptr,
			TEXT(
				"Mismatched Debug/Release ...\n"
				"..."
			),
			TEXT("D++ Debug/Release mismatch"),
			MB_OK | MB_ICONERROR
		);
		// ...
}
#endif
// ...
```

Useful links:
[MessageBoxA requirements](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxa#requirements)
[MessageBoxW requirements](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxw#requirements)
