### ISSUE TITLE
Feature Request: Configurable audio receive tick interval

### ISSUE THREAD

**Issue by tt2468** [brainboxdotcc/DPP#1009]
**Is your feature request related to a problem? Please describe.**
The current audio system processes new voice channel audio data on a hardcoded 500ms interval. For applications intending to use the resulting audio data as real-time as possible, this is a total blocker, as it results in a minimum of 500ms of audio latency.

Line in question: https://github.com/brainboxdotcc/DPP/blob/ffa2653f7504a701735ed23cfb2d503648253a96/src/dpp/discordvoiceclient.cpp#L167

**Describe the solution you'd like**
Having the ability to set this interval manually would be very helpful. I've tested down to 10ms intervals and `dpp::on_voice_receive` with no issues.

**Describe alternatives you've considered**
There's no way to even receive the raw opus payloads directly. Alternative for me is to go back to discordgo (what I was previously using) in order to get realtime access to the RTP payloads as they come in.

**Additional context**
None

**Comment by Jaskowicz1** [comment]
Hm, I like the sound of this! I guess it wouldn't be too hard to have something where the cluster could have something like `bot.audio_interval(10)`. I'd like to see what others think of this and how we could implement it.

**Comment by Jaskowicz1** [comment]
My only concern with implementing this is what you stated in #1008, it caused the audio data to be "completely garbled". Of course, we'd need to figure how to fix that 😅

**Comment by Jaskowicz1** [comment]
Hmm, that is slightly alarming. If you can easily reproduce it, it may be
worth filing a bug report for it.

**Comment by Jaskowicz1** [comment]
The PR has been merged to implement this!
