### ISSUE TITLE
FindSodium.cmake should support MinGW

### ISSUE THREAD

**Issue by obfuscatedgenerated** [brainboxdotcc/DPP#1011]
**Is your feature request related to a problem? Please describe.**
I'd like to compile DPP from source in the [MSYS2 MinGW64](https://www.msys2.org/) environment for Windows, but FindSodium.cmake doesn't support the platform

**Describe the solution you'd like**
I'd like FindSodium to support this toolchain

**Alternative solutions**
- I could setup VCPKG and Visual Studio for compilation, but I'm more comfortable using my current tools
- I could use WSL2, but then the built library won't be compatible with Windows

**Additional context - CMake Log**
CMake version: 3.26.4
OS: Windows 10
G++ version: g++.exe (Rev2, Built by MSYS2 project) 13.2.0
Processor architecture: AMD64

```
-- INFO: Using VCPKG if detected
-- INFO: Configuring .rc resource script
-- Detected AMD64 AVX type: AVX2 (FLAGS: -mavx2)
CMake Error: Configuration aborted via debugging interface.
CMake Error at cmake/FindSodium.cmake:196 (message):
  this platform is not supported by FindSodium.cmake
Call Stack (most recent call first):
  library/CMakeLists.txt:120 (include)

**Comment by Jaskowicz1** [comment]
We do not support MinGW!

**Comment by obfuscatedgenerated** [comment]
I ended up compiling the library with MSVC and then using that with MinGW, and it seems to work fine for now

**Comment by Mishura4** [comment]
I'd recommend getting used to MSVC. MinGW is very hard to do anything else than a hello world program with, you'll find very little support across the board in libraries, it lacks a lot of features that both MSVC and g++ have. Perhaps you were taught "visual studio bad" and sought to use "g++" instead, MinGW is not g++ either. "Visual studio bad" is also information that is outdated by almost a decade.

PRs are welcome if you manage to make it work, however that would still be unofficially supported.

**Comment by Mishura4** [comment]
And yes you can also use WSL2, Visual Studio has integrated support. I write my bot to be compatible with Windows through MSVC, and Linux through clang++ and g++, using WSL2.

**Comment by obfuscatedgenerated** [comment]
MinGW has worked fine for me all these years, I've never gotten MSVC to work well for my environment 🤷‍♂️
To each their own I guess.
