### ISSUE TITLE
Accessing deleted timer in cluster::tick_timers

### ISSUE THREAD

**Issue by rept1d** [brainboxdotcc/DPP#1048]
**Git commit reference**
c9bfdeb532c874a844d67dd93eea2485361e3a5d

**Describe the bug**
If `cluster::tick_timers` is executed simultaneously with `cluster::stop_timer`, it's possible that when you loop over `scheduled` (in `tick_timers`) you end up with a deleted `timer_t*`.

**Expected behavior**
A timer should only be ticked and rescheduled if it was not deleted.

**Comment by braindigitalis** [comment]
creating a PR for this.
