### ISSUE TITLE
How to get a channel id on channel create?

### ISSUE THREAD

**Issue by AndraxFlow** [brainboxdotcc/DPP#1108]
I want to be able to create and delete text and voice channels.  My bot can create channels and delete them, when I copying the id manually, but I want automatically get the id to delete a channel. How can I get the id?

**Comment by KatCote** [comment]
Same. If it isn't possible to get ID on create, what other the method can be used to get it?

**Comment by Mishura4** [comment]
When creating a channel, the newly created channel should be sent back and present in the callback parameter (see https://dpp.dev/classdpp_1_1cluster.html#a66df9163f111cec5a180d642f521660a & https://dpp.dev/callback-functions.html)
