### ISSUE TITLE
std::basic_string<uint8_t> is broken for LLVM-19

### ISSUE THREAD

**Issue by ghost** [brainboxdotcc/DPP#1129]
**Describe the bug**
The `uint8_t` type is typedef'ed as `unsigned char` in glibc. However the support for `unsigned char` type has been removed from `std::char_traits` in libc++ according to https://reviews.llvm.org/D138307. This gives an "implicit instantiation of undefined template `std::char_traits<unsigned char>`" error, during build.

**To Reproduce**
1. Compile D++ using the latest libc++.

**System Details:**
 - OS: Linux

**Additional context**
I would like to know what could be the proposed fix for this? I wouldn't mind sending the PR.

**Comment by braindigitalis** [comment]
what thing in dpp actually causes the warning, under what compiler and version?

**Comment by braindigitalis** [comment]
I'm not sure this needs to be a string, perhaps a vector would suffice? it is important for it to be unsigned 8 bit wide elements though.

**Comment by DebuggingLife46** [comment]
Yeah, I agree.

**Comment by Jaskowicz1** [comment]
Any news on this?

**Comment by Mishura4** [comment]
Idk we just need to have someone pick this up

**Comment by Mishura4** [comment]
I can look into this next week

**Comment by Jaskowicz1** [comment]
> I can look into this next week

![image](https://github.com/brainboxdotcc/DPP/assets/46899449/259a0793-65a1-4d9b-89a6-bfab27c31a50)

**Comment by Mishura4** [comment]
No unfortunately I just got extremely busy 😔

**Comment by ruslan-ilesik** [comment]
I think we should close this issue.
