### ISSUE TITLE
Mingw integration/help

### ISSUE THREAD

**Issue by matt1309** [brainboxdotcc/DPP#1133]
Hi, 

I have a project that is entirely setup in mingw on windows (controversial I know). I've seen a few old issues around MSVC being the only option, is this still the case? I tried using vcpkg however sodium issues arose. 

Curious if others have continued down this path of fixing sodium and other undetected dependency issues or does it just end in a headache. 

Trying to decide what my easiest path is choose between fixing all the undetected dependency issues (if that's even possible) or migrating my entire project to visual studio mscv?

Thanks.

**Comment by Mishura4** [comment]
Yes. The information on the main page of the repository is up to date, we do not support MinGW.

Closing this because this is not an issue with DPP, you can ask around on the discord server, but I am not aware of anyone with a MinGW setup.

> Trying to decide what my easiest path is choose between fixing all the undetected dependency issues

Probably not.

> migrating my entire project to visual studio mscv

Probably yes, or clang-cl
