### ISSUE TITLE
Bug: can not install .rpm on Fedora40

### ISSUE THREAD

**Issue by Katze719** [brainboxdotcc/DPP#1142]
**Git commit reference**
The git commit reference of the version you are using, obtainable via `git show -s --format="%H"`

**Describe the bug**
Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides libsodium.so.23()(64bit) needed by libdpp-10.0.29-1.x86_64 from @commandline

**To Reproduce**
1. wget -O dpp.rpm https://dl.dpp.dev/latest/linux-x64/rpm
2. sudo dnf install ./dpp.rpm

**Expected behavior**
package schould be installed

**Screenshots**

**System Details:**
 - OS: Fedora40

**Additional context**

**Comment by Jaskowicz1** [comment]
HI there!

Just to make sure, you do have libsodium installed right?

**Comment by Katze719** [comment]
apparently you need a special version of libsodium:
`Package libsodium-1.0.19-4.fc40.x86_64 is already installed.`

**Comment by braindigitalis** [comment]
the 23 in libsodium isnt the version number, for some reason on debian they call it libsodium23, version 1.0.19.
Same in most redhat: https://rpmfind.net/linux/rpm2html/search.php?query=libsodium23

**Comment by Katze719** [comment]
there is no libsodium23 for fedora, only libsodium. so would it be fine if i make a symlink for that?

**Comment by braindigitalis** [comment]
i cant imagine it doing any harm, should work fine.
sodium retains binary compatibility quite well.

**Comment by Katze719** [comment]
maybe you guys can add that info to your install guide for .rpm packages on fedora
