### ISSUE TITLE
CMake FetchContent support?

### ISSUE THREAD

**Issue by Advik-B** [brainboxdotcc/DPP#1167]
So that I can use FetchContent to avoid pkg managers.

Like use FetchContent and the library will automatically be setup

**Comment by Jaskowicz1** [comment]
You don't add support for FetchContent, it pulls from git. You're still in charge of making sure you have the dependencies that D++ requires. A quick google search would tell you that, [see link](https://cmake.org/cmake/help/latest/module/FetchContent.html).

If you want to use D++ via FetchContent, do something like
```cmake
include(FetchContent)

FetchContent_Declare(dpp
  GIT_REPOSITORY https://github.com/brainboxdotcc/DPP.git
  GIT_TAG v10.0.30
)

FetchContent_MakeAvailable(dpp)
```

**Comment by Advik-B** [comment]
> Jaskowicz it is very insensitive of you to say words such as "you" and "it", they don't believe in pronouns!, you're going to make them cry!
> 
> ...Oh shoot I used pronouns too
> 
> Oh no I did it again
> 
> Help

Huh

**Comment by Advik-B** [comment]
> You don't add support for FetchContent, it pulls from git. You're still in charge of making sure you have the dependencies that D++ requires. A quick google search would tell you that, [see link](https://cmake.org/cmake/help/latest/module/FetchContent.html).
> 
> If you want to use D++ via FetchContent, do something like
> 
> ```cmake
> include(FetchContent)
> 
> FetchContent_Declare(dpp
>   GIT_REPOSITORY https://github.com/brainboxdotcc/DPP.git
>   GIT_TAG v10.0.30
> )
> 
> FetchContent_MakeAvailable(dpp)
> ```
> 
> You can then link to dpp like you would normally.

Ye but I want to statically link to dpp
Does setting
`BUILD_SHARED_LIBS` to `OFF` In CMake help?

**Comment by Mishura4** [comment]
We do on Linux, and yes that will do it
