### ISSUE TITLE
Darkmode for Note in documentation

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#119]
**Describe the bug**
Noteblock in darkmode in the documentation has white text color and light yellow as background so its unreadable.
Found this here [https://dpp.dev/commandhandler.html](https://dpp.dev/commandhandler.html)

**To Reproduce**
Turn on darkmode

**Expected behavior**
The text to be in dark (black or so...)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44061123/136676515-19690d23-107b-40d1-a823-73d3844a8cdd.png)

**System Details:**
 - OS: Linux Ubuntu
 - Firefox latest version on desktop

**Additional context**
-

**Comment by braindigitalis** [comment]
Hi, thanks so much for the report!

I've adjusted the colour of the notes to --note-color-darker which looks like this in light mode and dark mode:

![image](https://user-images.githubusercontent.com/1556794/136676988-98c61445-ea1e-4295-add8-55c2b9243a1e.png)

Please let me know if there are any other issues :)

**Comment by j200283** [comment]
I have the same problem in win10's darkmod with Microsoft Edge and Chrome

OS: Windows 10 pro (20h2 - x64)
Chrome latest version on desktop / Microsoft Edge

**Comment by j200283** [comment]
Sorry, I forgot to put the image
![image](https://user-images.githubusercontent.com/53667451/136752670-07efb508-4434-4436-a8c7-dcf1ccaa9151.png)

**Comment by braindigitalis** [comment]
should be fine now, let me know how it looks for you 😄
