### ISSUE TITLE
Invalid avatar url in guild member

### ISSUE THREAD

**Issue by underflowerror** [brainboxdotcc/DPP#1230]
**Git commit reference**
#1148 (actually happens on 10.0.28-10.0.30 afaik)

**Describe the bug**
dpp::guild_member class returns invalid avatar url.

**To Reproduce**
1. Get guild member class.
2. Call get_avatar_url()

**Expected behavior**
Valid user avatar from guild.

**Screenshots**
Not needed.

**System Details:**
 - OS: Windows.
 - Discord Web Client.

**Additional context**
Here is some examples, here is what DPP returns: `cdn.discordapp.com/guilds/{server_id}/{user_id}/{avatar_hash}.png`
And here is what discord uses: `cdn.discordapp.com/guilds/{server_id}/users/{user_id}/avatars/{avatar_hash}.png`

**Comment by Jaskowicz1** [comment]
Can confirm the url is incorrect (see [this link](https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints))! I can get a fix out in ~30 minutes maybe an hour.
