### ISSUE TITLE
slowmode in threads

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#132]
**Is your feature request related to a problem? Please describe.**
I want to be able to set the slowmode in threads.

**Describe the solution you'd like**
to have an argument in `channel_edit` for example or even better an argument directly in the `thread_create` method.

**Additional context**
I'm sure that this feature could help many people because spam prevention is important especially for big servers.

**Comment by braindigitalis** [comment]
This can now be set via the`rate_limit_per_user` value in `dpp::channel` which previously contained voice channel bit width, as such we can close this.
