### ISSUE TITLE
Can't add roles to users?

### ISSUE THREAD

**Issue by AndOrNo1ne** [brainboxdotcc/DPP#1322]
I have a slash command that I'm attempting to assign the user the role but there doesn't seem like a clear way of doing that. Am I missing something or is this not implemented?

**Comment by braindigitalis** [comment]
everything is implemented, did you look at cluster::guild_member_add_role?

https://dpp.dev/classdpp_1_1cluster.html#aeffb7f4f32ca342886a79692ed8fb416

**Comment by braindigitalis** [comment]
The issues section is probably not the best place for obtaining library help. For questions such as this it is probably better if you use the official discord server at https://discord.gg/dpp
