### ISSUE TITLE
Pointless test "unittest" discovered whitch CMake tests enabled.

### ISSUE THREAD

**Issue by Hypooxanthine** [brainboxdotcc/DPP#1327]
**Git commit reference**
ab0142be0199666bfdabc70b3b426ab7af5003db

**Describe the bug**
Pointless unit test "unittest" added when discovering tests with CMake.

**To Reproduce**
When creating a test solution for a bot using DPP, and using googletest, a test name "unittest" is added to the discovered tests list and will always fail. googletest url fetched : https://github.com/google/googletest/archive/03597a01ee50ed33e9dfd640b249b4be3799d395.zip
Happened in my VS Code environment.
Structure : 
- Bot_Lib (library) links dpp
- BotTests (executable) links GTest::gtest_main and Bot_Lib
- Bot (executable) links Bot_Lib and a main.cpp file

**Expected behavior**
Only my tests to be discovered.

**Screenshots**
![image](https://github.com/user-attachments/assets/c5e95a74-225b-456c-8e53-dad4d134366c)

![image](https://github.com/user-attachments/assets/74b58ab4-eff3-4cb9-a6d9-0abd3dc608aa)
Highlighted text looks to be the problem. When I remove it from my fetched dependencies, the "unittest" disappears.

**System Details:**
 - OS: Windows 11

**Comment by braindigitalis** [comment]
i dont get it. why is it pointless? we actively use this in our CI.

**Comment by braindigitalis** [comment]
im not even sure what you're doing. you're not supposed to build dpp as part of your own code like that.

**Comment by Hypooxanthine** [comment]
Oh, ok. I didn't understand why it was here. I was searching for a workaround to this but didn't find any.

I know I am not building the good way but I found it easier for cross-compatibility reasons: I'm coding on my windows, my Ubuntu and I am compiling on a raspberry pi 2B debian which is also my server. (An other reason is that I don't like Visual Studio a lot)

And with googletest, when I discover tests, this "unittest" suddenly appears and fails everytime, that is why I called it "pointless", sorry for the misunderstanding.

(Anyway, if you do not want to support such building process, you can close my ticket and take this as a simple feedback)

**Comment by Neko-Life** [comment]
you can pass `-DDPP_BUILD_TEST=OFF` to cmake if you don't want to build unittest
