### ISSUE TITLE
CMake issue with Threads on linux

### ISSUE THREAD

**Issue by Mar0xy** [brainboxdotcc/DPP#15]
It seems like whenever you try to compile the library on Ubuntu 20.04+ with CMake 3.16.0 the Threads part fails with:
undefined reference to pthread_create

I already looked up the issue on google but everything always leads to issues with the way stuff is linked.

The error log:
```
gmake[1]: Entering directory '/home/marie/Documents/Projects/DPP/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_68755.dir/src.cxx.o
/usr/bin/c++    -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_68755.dir/src.cxx.o -c /home/marie/Documents/Projects/DPP/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_68755
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_68755.dir/link.txt --verbose=1
/usr/bin/c++   -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_68755.dir/src.cxx.o  -o cmTC_68755 
/usr/bin/ld: CMakeFiles/cmTC_68755.dir/src.cxx.o: in function `main':
src.cxx:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.cxx:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.cxx:(.text+0x63): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_68755.dir/build.make:87: cmTC_68755] Error 1
gmake[1]: Leaving directory '/home/marie/Documents/Projects/DPP/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_68755/fast] Error 2


Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}
```

**Comment by braindigitalis** [comment]
This does not look to be a bug in D++ but cmake not finding something it needs. 

What version of g++ are you using?

**Comment by Mar0xy** [comment]
I tried all versions and according to --version it's using 10.2.0 for g++

**Comment by Mar0xy** [comment]
Alright, so after going ahead and seeing the deps folder again I noticed the submodules missing so i went ahead and re-extracted it and then it worked sorry about this Issue

**Comment by braindigitalis** [comment]
how odd! well, i'm glad it got it fixed! 👍 
let me know if you have any further questions

**Comment by Mar0xy** [comment]
Alright so I tried to compile the first example to test but it seems to just spit out undefined references 
![image](https://user-images.githubusercontent.com/8841466/117589610-e3970480-b12a-11eb-8d7a-5f4a4409aa8f.png)
