### ISSUE TITLE
Replace MinGW with mingw-64

### ISSUE THREAD

**Issue by SirObby** [brainboxdotcc/DPP#154]
MinGW refers to both MinGW 32 and 64
(64 being the newer one)
If I remember correctly we've only gotten mingw-64 working.

**Comment by SirObby** [comment]
mingw-w64

**Comment by braindigitalis** [comment]
is this simply a docs change, or are cmakelists changes required also?

**Comment by SirObby** [comment]
no no only docs

**Comment by SirObby** [comment]
and the readme
