### ISSUE TITLE
Linker error with libopus

### ISSUE THREAD

**Issue by Jm56Z** [brainboxdotcc/DPP#161]
When compiling the library itself, all files compile correctly, then, when `Linking CXX shared library libdpp.so`, I get the following error :
```
/usr/bin/ld: /usr/local/lib/libopus.a(decode_indices.c.o): warning: relocation against `silk_NLSF_EXT_iCDF' in read-only section `.text'
/usr/bin/ld: /usr/local/lib/libopus.a(celt_encoder.c.o): relocation R_X86_64_PC32 against symbol `tf_select_table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/dpp.dir/build.make:1943: libdpp.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/dpp.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
I tried using `cmake -D CMAKE_CXX_FLAGS=-fPIC ..` on an empty build directory, but it didn't change a thing.
I checked, libopus was compiled with -fPIC. I don't understand.

I followed the build instructions in the [docs](https://dpp.dev/buildlinux.html) :
```
git clone --recursive git@git.github.com:/brainboxdotcc/DPP
cd DPP
mkdir build
cd build
cmake .. //Also tried with -D CMAKE_CXX_FLAGS=-fPIC
make -j4 //I only have 4 cores on my CPU
```

Cmake does find libopus & libsodium correctly - here is the output of cmake .. on the empty build directory.
```
-- The CXX compiler identification is GNU 11.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found sodium: /usr/lib/libsodium.so (found version "1.0.18") 
-- Found Opus: /usr/local/include  
-- Sodium 1.0.18
-- Detected libsodium and libopus. VOICE support will be enabled
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1l")  
-- Building git version. Be aware git versions may be unstable!
-- Configuring done
-- Generating done
-- Build files have been written to: /[...]/DPP/build
```

I'm on Archlinux x86_64 5.15.4-arch1-1.
I have libopus and libsodium installed, and all packages are on their latest version (as of writing this) :
- g++ 11.1.0
- ld 2.36.1
- cmake 3.22.0
- lib32-opus 1.3.1-1 (installed from pacman - multilib)
- libsodium 1.0.18-2 (installed from pacman - extra)
- DPP commit [b85115b](https://github.com/brainboxdotcc/DPP/commit/b85115b185c848040a641983e6d7b7b1e28f2d37)

I'm sure the error is on my side, but I cannot tell what I'm doing wrong.

Edit: just tried with commit [8ab0ca5](https://github.com/brainboxdotcc/DPP/releases/tag/v9.0.14) with no luck.

**Comment by braindigitalis** [comment]
lib32-opus is 32 bit multilib.
Are you building dpp in 32 bit, with a 32 bit cross compiler? If not you need a 64 bit libopus.
The error message usually indicates you are trying to dynamic link a 32 bit shared object against 64 bit code.
Let me know what happens if you find the non lib32 opus and try again :)

**Comment by Jm56Z** [comment]
I couldn't find a 64bit version of opus, so I recompiled the library using `cmake -D CMAKE_C_FLAGS=-fPIC ..`, then just running `make -j4` in this package worked. I sure hope it won't break other dependencies...

Thanks for the help !
