### ISSUE TITLE
Helper for mentions

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#163]
**Describe the solution you'd like**
In discordpy you can get the mention string of a channel, member or role.
It would be nice if you can add this too.
Just a member or a getter that gives the mention of the member, channel or role.

i know i can create a mention easily by do something like `"<@" + std::to_string(member.id) + ">"`.
but having a member that makes this for you would make this even easier.

**Comment by SirObby** [comment]
can you elaborate what you mean by having a member?

**Comment by Commandserver** [comment]
i mean either a getter that returns that, or an attribute that have the mention. idk how exactly that could be realized

**Comment by Commandserver** [comment]
in python it was just `member.mention` and i was looking for a way to get the mention like that 😀

**Comment by braindigitalis** [comment]
Added in dev, will be merged to master soon:

https://github.com/brainboxdotcc/DPP/commit/503da9991fed03918f0a5539dcab992b96d22e30

Supports get_mention() method on user, guild_member, channel, role, emoji, also utility::timestamp() for formatting a timestamp
