### ISSUE TITLE
Add a size option for dpp::user::get_avatar_url()

### ISSUE THREAD

**Issue by Fubuki-gh** [brainboxdotcc/DPP#178]
**Is your feature request related to a problem? Please describe.**
For example, if you want to add a user's avatar to an embed as a thumbnail, you usually have the problem that the image is too small. 

**Describe the solution you'd like**
You can make avatars bigger by adding a ?size=1024 string after the url. 
Example without resize: https://cdn.discordapp.com/avatars/788468151200514088/5a9782e9f4f77c5ef60f97cb1206370a.png?
Example with resize: https://cdn.discordapp.com/avatars/788468151200514088/5a9782e9f4f77c5ef60f97cb1206370a.png?size=1024
As you can see the avatar is much bigger. 
My suggestion would be to add a size option  in get_avatar_url() -> get_avatar_url(uint32_t size).
This feature does exist in discord.js.

**Describe alternatives you've considered**
You could also make a separate dpp::utils function for it.

**Comment by braindigitalis** [comment]
I like this idea, I propose having the parameter have a default of 0 which makes it not request a specific size. this way it doesn't break any existing code.

**Comment by braindigitalis** [comment]
this is now added to `master` branch
