### ISSUE TITLE
Receive Combined audio from users

### ISSUE THREAD

**Issue by BaybaraEvgeny** [brainboxdotcc/DPP#180]
JDA can receive combined audio, it is very convenient. We need the same feature. 
Anyone who uses audio receive has to implement this feature by himself unfortunately.

Just combine all users' audio packets

**Comment by braindigitalis** [comment]
I can think of a few ways to do this via basic mixing of the raw audio stream. this is not hard to do and would not need any dependencies. it would just be basic maths.

**Comment by braindigitalis** [comment]
This is now available in master via the new event on_audio_receive_combined.
when it has had some testing it will be in the next 10.0.8 release

thanks for your patience!
