### ISSUE TITLE
helper for communication disabled on member object

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#185]
**Is your feature request related to a problem? Please describe.**
A helper method that indicates if a member's communication is disabled.

**Describe the solution you'd like**
A method in `guild_member`. something like `is_communication_disabled()`?!

**Additional context**
https://discord.com/developers/docs/resources/guild#guild-member-object-guild-member-structure

**Comment by braindigitalis** [comment]
added to dev branch :)
it'll be in master some time very soon.
