### ISSUE TITLE
global constant for the CDN host

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#194]
**suggestion from _Brain_**
> there's a comment in every use of it saying discord plan to change it, when they do changing it in one place will be much easier

like here https://github.com/brainboxdotcc/DPP/blob/master/src/dpp/guild.cpp#L162

**Comment by SirObby** [comment]
Another suggestion, is that we can add an if statement for if they changed it.
Then in a later commit remove the old code (and if statement) this would be so changes in the API don't break the lib.

**Comment by SirObby** [comment]
Like if the CDN in discordapp.com is moved to discord.com, use discord.com. Then in a later commit remove discordapp.com from the code.
