### ISSUE TITLE
user discriminator zero disappears

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#205]
**Describe the bug**
In discord, i have a discriminator of `0098`.
due its an `uint16_t` in dpp, the zeros disappear :(

**To Reproduce**
```c++
cout << "Member discriminator: " << user.discriminator << endl;
```
printing my discriminator:
> 98

**Comment by Commandserver** [comment]
ah that's why discord returns a string as the discriminator https://discord.com/developers/docs/resources/user#user-object-user-structure

**Comment by braindigitalis** [comment]
uh, this isn't a bug, it's down to you to format numbers!
something like this:
fmt::format("{}#{:04d}", u.username, u.discriminator);
