### ISSUE TITLE
guild_command_create does not edit the slashcommand permissions

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#212]
**Describe the bug**
the permissions of slash commands aren't working when using `guild_command_create`.

i found out that `guild_command_edit_permissions` inside the `cluster::guild_command_create` method always throw and error:

```
{"message": "Unknown application command", "code": 10063}
```
I found out that this happens because the given slash command needs an `id` but doesn't have one.

So #209 isn't fully fixed.

**To Reproduce**

add a lambda in `guild_command_create` like so:

```c++
void cluster::guild_command_create(const slashcommand &s, snowflake guild_id, command_completion_event_t callback) {
	this->post_rest(API_PATH "/applications", std::to_string(s.application_id ? s.application_id : me.id), "guilds/" + std::to_string(guild_id) + "/commands", m_post, s.build_json(false), [s, this, guild_id, callback] (json &j, const http_request_completion_t& http) mutable {
		if (callback) {
			callback(confirmation_callback_t("slashcommand", slashcommand().fill_from_json(&j), http));
		}

		if (http.status < 300 && s.permissions.size()) {
			guild_command_edit_permissions(s, guild_id, [](const confirmation_callback_t & e) {
				if (e.is_error()) {
					std::cout << e.http_info.body << std::endl;
				} else {
					std::cout << "success" << std::endl;
				}
			});
		}
	});
}
```

**Expected behavior**
the `guild_command_edit_permissions` method works

**Comment by braindigitalis** [comment]
this won't ever work because "s" doesn't contain the application id. you need to std::get the slashcommand returned inside the callback not reference the one you originally passed in. 

slashcommand passed in should not be a non const ref. is this up to date with master or dev branch?

**Comment by Commandserver** [comment]
> slashcommand passed in should not be a non const ref. is this up to date with master or dev branch?

ups, yeah it should be a const

**Comment by Commandserver** [comment]
> this won't ever work because "s" doesn't contain the application id. you need to std::get the slashcommand returned inside the callback not reference the one you originally passed in.

what do you mean? geting the slashcommand from where?

**Comment by braindigitalis** [comment]
see #215 to see what I mean

**Comment by Commandserver** [comment]
yeah, i got it :)

**Comment by Commandserver** [comment]
okay
