### ISSUE TITLE
messages_get throws an error / breaks the execution when set the limit higher than 100

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#227]
**Describe the bug**
`messages_get` breaks the execution when set the limit of messages higher than 100!

**To Reproduce**
```c++
try {
            bot.messages_get(845266528676468976, 0, 0, 0, 101, [](const dpp::confirmation_callback_t &event) {
                if (!event.is_error()) {
                    auto mm = get<dpp::message_map>(event.value);
                    cout << "success; amount of messages: " << mm.size() << endl;
                } else {
                    cout << "error: " << event.http_info.body << endl;
                }
            });
        } catch (const std::exception &e) {
            cout << "exception: "  << e.what() << endl;
        }
```

**Expected behavior**
it calls multiple api requests to get more than 100 messages

**System Details:**
- DPP 9.0.17

**Comment by braindigitalis** [comment]
you forgot to provide the details of the exception! A stack trace would be really useful too please 😄

**Comment by Commandserver** [comment]
oh yeah. tbh it dont throw any exception there for me, it just breaks the program with `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`. the guy who reported the bug got an exception

**Comment by braindigitalis** [comment]
this broken functionality has been removed.
It could be considered abusive to the api anyway, so had no place in the lib.
