### ISSUE TITLE
CMakeLists doesn't export `include/` include directory

### ISSUE THREAD

**Issue by atomheartother** [brainboxdotcc/DPP#232]
**Describe the bug**
This library doesn't export its `include/` path to other projects who may want to use it, meaning using a pure CMake build we can't include any of the `dpp` headers without manually including the `dpp` include directory. This doesn't follow modern CMake best practices.

**To Reproduce**
Make a simple project:
```
.
├── CMakeLists.txt
├── deps
│   └── dpp
└── src
    └── main.cpp
```

CMakeLists:
```cmake
cmake_minimum_required(VERSION 3.0)
project(cppbot VERSION "0.0.1")

set(CMAKE_CXX_STANDARD 17)

add_subdirectory(deps/dpp)

add_executable(cppbot)

target_sources(cppbot PRIVATE
  src/main.cpp
)

target_link_libraries(cppbot PRIVATE
  dpp
)
```

And just include the `dpp.h` header in `main.cpp`:
```cpp
#include <dpp/dpp.h>

int main() {
  dpp::cluster bot("zob");

  return 0;
}
``` 

**Expected behavior**
This program should compile as `dpp` should export its `include/` directory, which is then included in `cppbot` when `dpp` is added as a target library.

**Screenshots**
![image](https://user-images.githubusercontent.com/10134879/150685755-07049c91-812a-4f14-b018-f44072a38ab3.png)

**System Details:**
- Linux + Arch
- CMake 3.22.1
- gcc 11.1

**Comment by braindigitalis** [comment]
Although this isnt the intended use for dpp (you're supposed to install it systemwide with `make install`) i'd welcome a patch to make this work. Please submit a PR against the dev and i'll accept it into the code.

**Comment by atomheartother** [comment]
I understand it's not the way the library is meant to be used, but this is how moden CMake projects are shaping out to look, using programs like [CPM](https://github.com/cpm-cmake/CPM.cmake) to make the whole dependency process much easier. I'll look into a patch right away :)

**Comment by braindigitalis** [comment]
thanks, ive merged your PR in :)

**Comment by atomheartother** [comment]
You're welcome! 

For future reference, the PR in question: #233
