### ISSUE TITLE
member not populated correctly

### ISSUE THREAD

**Issue by Jerem584** [brainboxdotcc/DPP#256]
**Describe the bug**
in the event (on_interaction_create) 

-> event.command.member is not being populated correctly
it only have nick, and roles. which is a problem.

the event.raw_event got all informations tho 

**To Reproduce**
Create an interaction, 
add the on_interaction_event

add this line to print member info 
`printf("info = %s\n", (event.command.member.build_json()).c_str());
`

**Expected behavior**
member to be populated correctly

**System Details:**
v9.0.18

**Comment by Commandserver** [comment]
You shouldn't use `build_json()` to check if the attributes are set correctly, it is used for actions like modify a guild member and does not contain all informations
