### ISSUE TITLE
Application Command Attachments

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#268]
**Describe the solution you'd like**
Attachments on slash commands
![grafik](https://user-images.githubusercontent.com/44061123/153582312-710949e0-fcde-443a-a221-49e037b76366.png)
Official Discord announcement:
https://discord.com/channels/613425648685547541/697138785317814292/940762083820175440

**Comment by braindigitalis** [comment]
now implemented in master
