### ISSUE TITLE
Complete guild object

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#270]
**Is your feature request related to a problem? Please describe.**
Some fields like `premium_progress_bar_enabled`... in `dpp::guild` are missing

**Describe the solution you'd like**
to add them

**Additional context**
Official discord resource:
https://discord.com/developers/docs/resources/guild#guild-object

**Comment by braindigitalis** [comment]
they're not missing they're compressed into the flags

**Comment by braindigitalis** [comment]
I have no plans to add any extra lists like stickers and stage instances, scheduled events etc to the guild structure.

we have to consider the size of the guild structure and that it's multiplied up by however many guilds you are on. there are API calls in DPP to get these lists.

I'm pretty sure a lot of the flag stuff like premium progress bar is stuffed into flags, if not this is where it belongs.

**Comment by braindigitalis** [comment]
hmm, I wonder if it's possible to just add lists of the snowflake IDs like we do for emojis...
