### ISSUE TITLE
equivalent to .exe for linux?

### ISSUE THREAD

**Issue by dtpfl** [brainboxdotcc/DPP#276]
Hey, im trying to use your library in pascal programming language.

For Windows this doesn't seem too complicated because there is a DPP.dll, where i can call functions from.
But for Linux i havent found any solution yet. 

Maybe i missed something...
This could also be a suggestion for adding .so or .a files.

![image](https://user-images.githubusercontent.com/15970071/154111276-b3583d5d-ad9b-49c4-8d0a-c4e7a3005119.png)

**Comment by braindigitalis** [comment]
you won't be able to use this in pascal.
it uses C++ templates, operator overloading, lambdas and a ton of other C++ specific (not C) stuff that pascal does not have.
