### ISSUE TITLE
helper function for slash command registration

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#285]
**Is your feature request related to a problem? Please describe.**
registering slash commands in `on_ready`

**Describe the solution you'd like**
`exec_once`.
Discord conversation: https://discord.com/channels/825407338755653642/825407339254644779/942795789493735474

**Comment by braindigitalis** [comment]
decided to call it `run_once`, because exec says to most people that it runs an executable...
it'll be in master later tonight.

**Comment by es183923** [comment]
i think it should be `cluster::on_once`. This makes it have the same format as all the other functions that are similar.

**Comment by braindigitalis** [comment]
it isnt an event though, its a helper template, events are called on_*
