### ISSUE TITLE
Message content is empty in a on_message_create event

### ISSUE THREAD

**Issue by lifegame1lu111** [brainboxdotcc/DPP#315]
**Describe the bug**
The dpp::message_create_t::msg::content field is empty in a on_message_create event.

**To Reproduce**
```
#include <dpp/dpp.h>
#include <iostream>
int main(){
      dpp::cluster bot("tkn");
      bot.on_message_create([&](const dpp::message_create_t& event){
            std::cout << event.msg.content;
      });
}
```
then send something in a discord channel,
nothing will be printed to the console.

**Expected behavior**
The event.msg.content field to get printed to stdout.

**System Details:**
 - OS: Windows 11
 - Discord Client used for testing: Web

**Additional context**
The bot token is a legit bot account and is unverified.

**Comment by es183923** [comment]
If you're using DPP (<https://dpp.dev>) v10.x.x and you find that the message content is blank, that means you may need to add the `message_content` intent to your bot. This is not a default intent for DPP, as this is a privileged intent. You can do add the `message_content` intent in the second parameter of the bot initialization.

You will also need that you may need to enable the message content intent. You can do this by going to <https://discord.com/developers/applications>, selecting your bot, clicking the **Bot** category, and then enabling it in the **Priveledged Gateway Intents** category.

Example:
```cpp
#include <dpp/dpp.h>
int main() {
    uint64_t intents = dpp::i_default_intents <s> dpp::i_message_content;
    dpp::cluster bot("YOUR_BOT_TOKEN", intents); // note the second parameter here
    // rest of your code
}
```
You can see all the intents here: <https://dpp.dev/namespacedpp.html#a0042c0fc8164da4239b977d5be8e2ef5>

**Comment by lifegame1lu111** [comment]
Ah, yes im using v10.x.x versions, will enable the intents in the page

**Comment by Henonicks** [comment]
> If you're using DPP (https://dpp.dev) v10.x.x and you find that the message content is blank, that means you may need to add the `message_content` intent to your bot. This is not a default intent for DPP, as this is a privileged intent. You can do add the `message_content` intent in the second parameter of the bot initialization.
> 
> You will also need that you may need to enable the message content intent. You can do this by going to https://discord.com/developers/applications, selecting your bot, clicking the **Bot** category, and then enabling it in the **Priveledged Gateway Intents** category.
> 
> Example:
> 
> ```c++
> #include <dpp/dpp.h>
> int main() {
>     uint64_t intents = dpp::i_default_intents | dpp::i_message_content;
>     dpp::cluster bot("YOUR_BOT_TOKEN", intents); // note the second parameter here
>     // rest of your code
> }
> ```
> 
> You can see all the intents here: https://dpp.dev/namespacedpp.html#a0042c0fc8164da4239b977d5be8e2ef5

Every time I launch my bot, the console keeps saying this:
```[Sat May  6 15:41:44 2023] WARN: OOF! Error from underlying websocket: 4014: Disallowed intent(s)
[Sat May  6 15:41:44 2023] DEBUG: Attempting reconnection of shard 0 to wss://gateway.discord.gg
[Sat May  6 15:41:48 2023] DEBUG: Connecting new session...```
...over and over again

**Comment by Axyte** [comment]
Did you enable them on the developer portal?

**Comment by braindigitalis** [comment]
why are you bumping this closed issue? You'll do better asking about this on discord if you're still stuck with it.

**Comment by Henonicks** [comment]
> why are you bumping this closed issue? You'll do better asking about this on discord if you're still stuck with it.

It seems that Discord server died

**Comment by braindigitalis** [comment]
What, https://discord.gg/dpp ? It most definitely is not dead. Patience is required.
