### ISSUE TITLE
Can I build D++ for static linking?

### ISSUE THREAD

**Issue by MasFlam** [brainboxdotcc/DPP#34]
The makefiles cmake generates only seem to build a shared object. Is there a way to compile the library into an archive instead?

**Comment by braindigitalis** [comment]
Yes but currently only on the dev github branch. After switching to the dev github branch, the build flag `-DBUILD_SHARED_LIBS=OFF`

**Comment by MasFlam** [comment]
All seems to be working, thank you for the help. I'm also wondering, is there a way for stopping and disconnecting a `dpp::cluster`?

**Comment by braindigitalis** [comment]
not really, as discord doesn't have a quit command as such, you just disconnect the websocket and discord times it out later.

so, you could call cluster::start with true as a parameter and run your own sleep/loop afterwards, when you want to end the cluster call it's destructor and it will close it's sockets. I haven't tested this ability much though as most discord bots are dedicated processes and not embedded in something else.

**Comment by MasFlam** [comment]
I sleep 10 seconds and then `delete` my cluster but the bot stays running. I don't *really* need this I guess, I can just run the bot from a shell script and sigint the process whenever i need to, so no big deal.

Thanks again for help and for this awesome library; I'm gonna rename the issue so that it will show up when searching for stopping a cluster too.
