### ISSUE TITLE
Warnings for specific event routers should be suppressable

### ISSUE THREAD

**Issue by OtoshigamiX** [brainboxdotcc/DPP#357]
**Is your feature request related to a problem? Please describe.**
I'm writing a bot which needs only access to DM messages, and using on_message_create with only default intents causes a warning to be printed out with each message received. DM messages can be read without this intent, so I'd want to suppress this warning.

**Describe the solution you'd like**
I would like to suppress warnings on event_handlers, ideally not every warning, but only those that I know that I can ignore. 

**Describe alternatives you've considered**
Adding missing intent, but this requires additional perms for the bot, which won't be used for this particular bot

**Comment by braindigitalis** [comment]
now fixed in dev, will not emit the warning for DMs, thanks for the report!
