### ISSUE TITLE
Support followup messages

### ISSUE THREAD

**Issue by es183923** [brainboxdotcc/DPP#358]
**Is your feature request related to a problem? Please describe.**
D++ doesn't support folllowup messages.

**Describe the solution you'd like**
Add support for them

**Describe alternatives you've considered**
Constructing webhooks and using that instead webhooks to do it. It does work, but isn't as nice as a dedicated function, as this is part of the official API docs.

**Additional context**
links:
https://discord.com/developers/docs/interactions/receiving-and-responding#followup-messages
https://discord.com/developers/docs/interactions/receiving-and-responding#create-followup-message

**Comment by braindigitalis** [comment]
this is now added in dev!
