### ISSUE TITLE
Stuff

### ISSUE THREAD

**Issue by HideakiAtsuyo** [brainboxdotcc/DPP#362]
Add usefull stuff 😳 

```cpp
bot.on_message_create([&bot](const dpp::message_create_t& message) {
//Example:
if(message.author.bot) return;
		message.reply("ok");
		});
```
message.**author** should be added with: (send, user object (bot boolean, user id, username, discriminator etc..))

**Comment by HideakiAtsuyo** [comment]
Instead of message.msg

**Comment by HideakiAtsuyo** [comment]
+ in bot client add <bot>.user that should contain bot infos

**Comment by braindigitalis** [comment]
eh what
you need to actually read the documentation for this lib rather than assuming its going to be like something else you used.
There are reasons for the design of the library, it would not make sense to have a bool for `.bot`...

You need to do `bot.me.username`

please read the documentation: https://dpp.dev

If you need further help please go to the discord server: https://discord.gg/dpp

**Comment by braindigitalis** [comment]
> Instead of message.msg

no, you decided to call it message.... its an event object, you should probably call it event.
`event.msg.author.is_bot()`

**Comment by HideakiAtsuyo** [comment]
> eh what you need to actually read the documentation for this lib rather than assuming its going to be like something else you used. There are reasons for the design of the library, it would not make sense to have a bool for `.bot`...
> 
> You need to do `bot.me.username`
> 
> please read the documentation: https://dpp.dev
> 
> If you need further help please go to the discord server: https://discord.gg/dpp

My suggestion is to move \<message event>.msg to \<message event> and \<bot client>.me to \<bot client>.user + I already figured the is_bot out :)

**Comment by braindigitalis** [comment]
no.... you cant move the message struct into the event, the event is a container class...

**Comment by braindigitalis** [comment]
plus, theres a type called user, so you cant also have a variable called user inside an object.

```cpp
namespace dpp {

class cluster {
    user user;
}

};
```

how would this work?

**Comment by HideakiAtsuyo** [comment]
> plus, theres a type called user, so you cant also have a variable called user inside an object.
> 
> ```c++
> namespace dpp {
> 
> class cluster {
>     user user;
> }
> 
> };
> ```
> 
> how would this work?

Yeah true I'm just based on how discord.js work it's pretty well thought so I thought it would be possible to do a rewrite for it🤔

**Comment by HideakiAtsuyo** [comment]
Moved to Discord
