### ISSUE TITLE
Can't send webhooks with attachments

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#399]
**Git commit reference**
6cf7c038d4b37364bde1b654f4fbb65e0a44464f

**Describe the bug**
When i send a message with an attached file using `execute_webhook`, it only sends the message.

**To Reproduce**
1. create a message object
2. attach a file to it with `add_file`
3. run `bot.execute_webhook` with this message
4. The file doesn't show up

**Expected behavior**
The message and the file to be sent

**Comment by braindigitalis** [comment]
thanks, added in 7841ab57aff30a349edcaabfe2d1f6b70d1743e8
