### ISSUE TITLE
cluster::guild_edit_member throws `Target user is not connected to voice`

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#417]
**Git commit reference**
7e61fdcb02b5f7a021cf3fcdd10e8c6134d61a96

**Describe the bug**
when calling `cluster::guild_edit_member`, discord tells
> Target user is not connected to voice

**To Reproduce**
call the method and pass a member who is not connected to voice

**Expected behavior**
edits the member (e.g. changes the nickname).

**Additional context**
seems to be the `mute` and `deaf` [json params](https://discord.com/developers/docs/resources/guild#modify-guild-member) that causes this issue because they're set even if the member is not in voice.

**Comment by unsigned-ru** [comment]
Yeah, i found this bug and reported this in the discord, trying something right now, testing if it worked.

**Comment by unsigned-ru** [comment]
Okay so, my guess is that the issue that the mute and deaf are always true and false no matter what. These are nullable parameters. If you don't want to change the user state in the voice channel then these have to be null. Which they are never.
