### ISSUE TITLE
permissions getter for members

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#425]
**Describe the solution you'd like**
would be nice to add a method to `dpp::guild_member` to get the base permissions.
A similar method like `dpp::guild::base_permissions`.

**Comment by harshfeudal** [comment]
Aren’t we have this method to do?
`guild_find->base_permissions(&event.command.usr).has(dpp::p_kick_members)`

I think it still better to use tho.

**Comment by braindigitalis** [comment]
seems like it would just be a shortcut to the existing methods in channel and guild?
