### ISSUE TITLE
Gateway connection does not close gracefully

### ISSUE THREAD

**Issue by theyarelulu** [brainboxdotcc/DPP#431]
**Git commit reference**
[45c509f](https://github.com/brainboxdotcc/DPP/commit/45c509fb763f0b6d34494d546c802986ac15d648)

**Describe the bug**
The library does not seem to be closing the gateway socket properly. After the cluster terminates, the bot will still be online for a while, indicating Discord did not receive a closure signal.

**To Reproduce**
1. Call `start(true)` on the cluster
2. Sleep for 10 seconds
3. Call `terminating.notify_all()` on the cluster 
4. Sleep for 10 seconds

**Expected behavior**
The gateway would shutdown gracefully, and the bot user would go offline immediately, indicating a clean shutdown.

**System Details:**
 - OS: ubuntu focal (using DPP's official docker image)
 - Discord Client used for testing: desktop

**Comment by theyarelulu** [comment]
I have no objection to it being an optional feature, and I totally understand the reasoning. Maybe just like how the start function takes a `boolean`, make a close function that also takes a boolean in regards to blocking the thread. Seems symmetrical to me

**Comment by es183923** [comment]
You could have a function on the bot object that changes a parameter in the bot itself, that would affect the destructor behavior, like this: 
```cpp
#include <iostream>

struct S {
    bool clean_stop{false};
    S& set_clean_stop(bool c) {
        clean_stop = c;
        return *this;
    }
    ~S() {
        if (clean_stop) {
            std::cout << "do stuff to cleanly stop\n";
        } else {
            std::cout << "don't cleanly stop\n";
        }
    }
};

int main() {
    S s;
    s.set_clean_stop(true);
}
```
