### ISSUE TITLE
Mutex includes broken with the new DNS feature

### ISSUE THREAD

**Issue by Eremiell** [brainboxdotcc/DPP#434]
**Git commit reference**
4eacb0c99c799fd90574835eef0fa641dfae3185 (10.0.12)

**Describe the bug**
The new DNS feature uses unique_lock with shared_mutex. This requires \<mutex\> header included on gcc 11+ and clang 12.0.1+. (MSVC wasn't explicitly tested, but can follow the suite anytime if they don't do so yet.) Older versions of standard libraries likely allowed omitting this due to indirect inclusion.

**To Reproduce**
1. Attempt building the library on gcc 11+ or clang 12.0.1+

**Expected behavior**
Library builds without errors.

**System Details:**
 - Translation Suite: gcc 11+ or clang 12.0.1+

**Additional context**
Godbolt links demonstrating the issue and its fix:

gcc broken: https://godbolt.org/z/1oTe8336o
clang broken: https://godbolt.org/z/Kc6K1Gf3c
gcc fixed: https://godbolt.org/z/3Pd67PxoY
clang fixed: https://godbolt.org/z/3exYzv894

Reference:

shared_mutex example including \<mutex\>: https://en.cppreference.com/w/cpp/thread/shared_mutex#Example
unique_lock being defined in \<mutex\>: https://en.cppreference.com/w/cpp/thread/unique_lock

PR will follow shortly.

**Comment by braindigitalis** [comment]
merged the fix with thanks!
