### ISSUE TITLE
Dissalowed intent for i_message_content

### ISSUE THREAD

**Issue by Senya247** [brainboxdotcc/DPP#439]
I added the ```i_message_content``` intent to my bot by setting its intents to ```dpp::i_default_intents | dpp::i_message_content```, but when I tried running the bot, i got the "Dissallowed intent(s)" error. My bot has administrator privileges, how do I do this right?

**Comment by Commandserver** [comment]
You need to enable the message content intent the developer portal too: https://discord.com/developers/applications
Select your bot, Click the Bot category, and then enabling it in the Priveledged Gateway Intents category. Check the image:
![image](https://user-images.githubusercontent.com/44061123/177035028-6bd2aa06-4e75-442e-9e1e-16a5b8a3a432.png)

**Comment by Senya247** [comment]
@Commandserver Thank you! But is there a reason why I don't need to do this, for example, in discord.py? Using that library I could just use the ```on_message``` function.

**Comment by es183923** [comment]
Because it does not follow the docs properly, and this is is a priviledged intent and should not be enabled by default.  It also uses the API version 7, which extremely old
