### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by KiNa738** [brainboxdotcc/DPP#444]
**Git commit reference**
The git commit reference of the version you are using, acff672b6ecc3639853238c1dabb91be55bfe830

**Describe the bug**
DPP/src/dpp/sslclient.cpp:286:32: error: ‘TLS_client_method’ was not declared in this scope;
286 |     const SSL_METHOD *method = TLS_client_method(); /* Create new client-method instance */

**To Reproduce**
Build Source Code
cmake -B ./build
cmake --build ./build -j8

**Screenshots**
![image](https://user-images.githubusercontent.com/52557976/180052623-21a17de6-ff97-481e-9f1c-37b3f23c9480.png)

**System Details:**
 - OS: Ubuntu 20.04.4 LTS

**Comment by braindigitalis** [comment]
works fine on GitHub action, do you have openssl-dev installed?

you could try installing the .deb from the release instead.

**Comment by braindigitalis** [comment]
I've done some research and it seems you may be using a version of openssl that is outdated and does not support the correct TLS protocols required by discord. Have you successfully compiled this before?

what openssl version is it?

**Comment by KiNa738** [comment]
thank you i was searching too, sudo apt-get install libssl-dev solved the problem. sorry for the trouble <3.

**Comment by braindigitalis** [comment]
no problem! I'll close this issue now
