### ISSUE TITLE
Could NOT find sodium (missing: sodium_LIBRARY_RELEASE sodium_LIBRARY_DEBUG)

### ISSUE THREAD

**Issue by abdfnx** [brainboxdotcc/DPP#458]
**Describe the bug**
Hi, when I tried to build `dpp` from source, I run `cmake -B ./build` then it's failed because `sodium` package is not found, although I downloaded the package (`libsodium-dev`)

**Screenshots**
![Web capture_4-8-2022_17339_abdfnx-botway-q7qpqjxrg295rr github dev](https://user-images.githubusercontent.com/64256993/182866755-6895dda8-7b01-47e8-baff-2123fc94bfb9.jpeg)

**System Details:**
 - OS: Ubuntu
 - Discord Client used for testing: web

**Comment by Axyte** [comment]
Install `pkg-config` and retry.

**Comment by abdfnx** [comment]
> Install `pkg-config` and retry.

it's already installed

**Comment by braindigitalis** [comment]
what is linuxbrew?

**Comment by braindigitalis** [comment]
does your OS not have a proper package manager? homebrew is problematic enough on osx...

**Comment by abdfnx** [comment]
> does your OS not have a proper package manager? homebrew is problematic enough on osx...

it's ubuntu, and the package manager is `apt-get`

and I've used `homebrew` just to install `openssl`

**Comment by braindigitalis** [comment]
apt install pkg-config openssl-dev zlib1g-dev opus-dev libsodium-dev?

**Comment by abdfnx** [comment]
thanks for your time, the issue has been resolved
