### ISSUE TITLE
Cannot run dpp on a Raspberry PI: error on https connection to discord.com:443: Connection timed out

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#461]
**Git commit reference**
018a8612115e5821b0adf9e26b4d1224de555835

**Describe the bug**
i get this error when i try to run my discord bot on a raspberry pi 4 model B **using D++ v10.0.15**:
```
HTTP(S) error on https connection to discord.com:443: Connection timed out
terminate called after throwing an instance of 'dpp::connection_exception'
  what():  Auto Shard: Cannot determine number of shards. Cluster startup aborted. Check your connection.
Aborted (core dumped)
```

**To Reproduce**
1. Install dpp v10.0.15
2. I used [this](https://dpp.dev/buildcmake.html) guide to make my discord bot
3. execute the compiled bot

**Expected behavior**
The bot to start.

**System Details:**
 - OS: Ubuntu 20.04.4
 - Discord Client used for testing [desktop]

**Additional context**
I checked my internet connection and it's working. The raspberry also currently runs another bot in python, so i bet it's not the internet connection. And i also don't have any special firewalls, of curse.

**Comment by lifegame1lu111** [comment]
This bug also happens on android

**Comment by Commandserver** [comment]
Seems to be fixed and works now with the release of dpp version `10.0.17` 🎉
