### ISSUE TITLE
Cannot respond to slash command interactions triggered in a DM channel

### ISSUE THREAD

**Issue by lifegame1lu111** [brainboxdotcc/DPP#465]
**Describe the bug**
Responding to slash commands fails in DMs with exception nlohmann::type_error on windows.

**DPP version**
Release 10.0.15

**To Reproduce**
Run any slash command in a DM channel.

**Expected behavior**
The bot responds to the interaction just like in a guild channel or thread channel.

**System Details:**
OS: Windows 11 22H2

**Additional context**
All intents are declared in dpp::cluster construction.

**Comment by braindigitalis** [comment]
this should be fixed in master branch, please try it and let me know. Thanks for the report!
