### ISSUE TITLE
Stack smashing detected

### ISSUE THREAD

**Issue by JeanMarcZimmer** [brainboxdotcc/DPP#501]
Lib version : Release 10.0.18 from the AUR (10.0.18-1), I believe commit 6832533

Pretty sure I have something weird on my computer, but I can't find out what, since Valgrind isn't working on Arch-based kernels at the moment.
Just declaring the `dpp::cluster` variable at the beginning of the program throws the error :
```
*** stack smashing detected ***: terminated
IOT instruction (core dumped)
```

My main.cpp is

```c++
#include <dpp/dpp.h>

int main(int argc, char **argv)
{
    dpp::cluster bot("[TOKEN]");
    return 0;
}
```
The program returns 134.

Weirdly enough, if I left the rest of the example code, I just get a segfault - although I guess it comes from that initial error.

System Details:
 - OS: Manjaro Linux x86_64, kernel 5.15.60-1-MANJARO
 - host : Acer Nitro AN515-45 (the linux kernel comes from the packages `linux515-XXX`)

**Comment by braindigitalis** [comment]
I can't duplicate this,
you need to actually debug it, does gdb work for you?

**Comment by braindigitalis** [comment]
trying to Google this results in tons of similar issues across dozens of programs... does manjaro have a problem?

https://www.google.com/search?q=manjaro%20iot%20instruction

**Comment by JeanMarcZimmer** [comment]
> trying to Google this results in tons of similar issues across dozens of programs... does manjaro have a problem?
> 
> https://www.google.com/search?q=manjaro%20iot%20instruction

That would make sense. Quite annoying as I can't get Arch to work on my machine (NVidia keeps screwing things up)
