### ISSUE TITLE
Forums

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#506]
**Feature Request**
Implement the new Forum channels.

**Additional context**
https://discord.com/developers/docs/change-log#sep-14-2022

**Comment by braindigitalis** [comment]
pretty sure we already have these?

**Comment by Commandserver** [comment]
They've updated a few things iirc

**Comment by braindigitalis** [comment]
there are no updates to the docs?

**Comment by Axyte** [comment]
https://discord.com/developers/docs/topics/threads#forums
