### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Matix2021** [brainboxdotcc/DPP#511]
I have a problem with the latest package of D++
I did exactly according to this guide: https://dpp.dev/buildcmake.html
but when compiled with "cmake --build."
returns an error:
![unknown](https://user-images.githubusercontent.com/82207406/191574639-e04bbb52-cdd4-46d9-8fd8-f78119809910.png)

Editor: Visual Studio Code (Version: 1.17.2)
Compiler: gcc (Version: 11.2.0) and CMake (Version: 3.24.2)
System: Windows 10 pro 64bit

**Comment by Matix2021** [comment]
but I want to program it using Visual Studio Code and CMake.

**Comment by braindigitalis** [comment]
> but I want to program it using Visual Studio Code and CMake.

have fun then! We can't support every random choice of compiler people decide they want to do. If you're NEW to C++, choose the actual easy, supported option, don't try and go it alone.
