### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by NoAimPureLuck** [brainboxdotcc/DPP#521]
/usr/bin/ld: warning: libssl.so.3, needed by /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_CTX_new@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_pending@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_read@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_CIPHER_get_name@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_write@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_ctrl@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_new@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_set_fd@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_CTX_ctrl@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_get_error@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `TLS_client_method@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_shutdown@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_free@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_get_current_cipher@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `SSL_connect@OPENSSL_3.0.0'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `pthread_create@GLIBC_2.34'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libdpp.so: undefined reference to `pthread_cond_clockwait@GLIBC_2.34'
collect2: error: ld returned 1 exit status

**Comment by AmundDynna** [comment]
compiler setting

{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-std=c++17",
                "-ggdb",
                "-Og",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}",
                "-ldpp"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "compiler: /usr/bin/g++"
        }
    ]
}

**Comment by Axyte** [comment]
Update your distro, install openssl3, or build D++ yourself,

**Comment by AmundDynna** [comment]
I am using the latest version of wsl2 Ubuntu so openssl should be already installed

**Comment by Axyte** [comment]
*Which* version? 22.04?

**Comment by AmundDynna** [comment]
Using the default Ubuntu for wsl2

**Comment by braindigitalis** [comment]
the default is 20.04. you have to upgrade it
