### ISSUE TITLE
Disable voice support in xmake

### ISSUE THREAD

**Issue by Commandcracker** [brainboxdotcc/DPP#544]
Is there some way to disable voice support when building with xmake, like in cmake `BUILD_VOICE_SUPPORT`

**Comment by Bricklou** [comment]
Hi,
I'm the maintainer of the xmake package of DPP.
There is no way to disable the voice support, but I can take a look to add it. Don't hesitate to suggest something if you find how to do that.

**Comment by Commandcracker** [comment]
This might help: [xmake_configuration_option](https://xmake.io/#/manual/configuration_option).

$ xrepo info dpp
![Screenshot_20221103_132221](https://user-images.githubusercontent.com/49335821/199719216-d1fdb8d5-61aa-4531-9c88-d416535eb49e.png)
Setting some compiler flag cud also be a solution, but it would be easier for the end user with an [configuration_option](https://xmake.io/#/manual/configuration_option).

**Comment by SirObby** [comment]
Seems like it would be possible.

**Comment by Bricklou** [comment]
I made the change, i'm waiting for my PR to be approved: xmake-io/xmake-repo#1596

**Comment by Bricklou** [comment]
The PR has been merged.
