### ISSUE TITLE
CMake: Rework compiler flags

### ISSUE THREAD

**Issue by NexAdn** [brainboxdotcc/DPP#595]
**Is your feature request related to a problem? Please describe.**

The current build system configuration doesn't allow for custom compiler flags to be set.
This can cause problems for packagers if DPP behaves problematic with the default flags.

Looking at the current build system, there is a strong indication that it has historically grown,
showing high levels of code duplication, at least in the compiler flag setting part.
Furthermore, the system appends certain flags after the user-specified ones which overwrite user-specified flags.
Additionally, stuff like `-fPIC`, which is automatically enabled for libraries by CMake is set explicitly here,
only increasing the flag list for no reason.
The same goes for `-std=c++17` and CMake automatically deducing the required C++ standard from `target_compile_features()`.
Lastly, the flag setting checks for the build type using `if()` blocks,
while CMake also offers build type specific variables for setting compiler flags.
These can reduce the amount of branching in the CMakeLists.txt drastically.

https://github.com/brainboxdotcc/DPP/blob/788377d2b4fef949db3debd02d9acaea37344eff/library/CMakeLists.txt#L165-L186

**Describe the solution you'd like**

Ideally, the flag setting part of the CMakeLists.txt is reworked,
dropping all the unneeded flags and/or replacing them by the proper CMake mechanisms for determining the correct flags.

**Describe alternatives you've considered**

Keeping the hard to read and maintain status quo. However, this doesn't support overwriting certain compiler flags.

**Additional context**

First reported by the Gentoo Tinderbox: https://bugs.gentoo.org/890014

**Comment by asarubbo** [comment]
> First reported by the Gentoo Tinderbox: https://bugs.gentoo.org/890014

I'm the author of th original downstream report. The affected flag is just `-Os` that overwrites the -O flag set by the user.

```
 * Tinderbox QA Notice: This package seems to overwrite CFLAGS/CXXFLAGS or add uncommon ones:
 *   The following flags (probably added by the build system) should be stripped out
 * 
 *   1) -Os
```

**Comment by braindigitalis** [comment]
i dont agree with trying to deduce the c++ version. This should be explicitly set to C++17 for non-coro and C++20 for coro, as it isnt all down to the compile features in DPP.
The rest i'm down for. However, if we're tidying this, to avoid copy and pasting, can we tidy the warning flags into a variable? Notably these: `-Wall -Wno-psabi -Wempty-body -Wignored-qualifiers -Wimplicit-fallthrough -Wmissing-field-initializers -Wsign-compare -Wtype-limits -Wuninitialized -Wshift-negative-value` - these are carefully selected as -Wall has different effects and list of warnings in e.g. clang compared to g++.

**Comment by braindigitalis** [comment]
> > i dont agree with trying to deduce the c++ version.
> 
> I never used that one on my projects either. But I am still in favor of letting CMake automatically set the correct compiler flags, while telling it which standard to use, i.e. `target_compile_features(... cxx_std_17)` or `target_compile_featuers(... cxx_std_20)`. That's already done in the CMakeLists.txt, but for some reason we still set `-std=c++17` explicitly:
> 
> https://github.com/brainboxdotcc/DPP/blob/788377d2b4fef949db3debd02d9acaea37344eff/library/CMakeLists.txt#L179
> 
> https://github.com/brainboxdotcc/DPP/blob/788377d2b4fef949db3debd02d9acaea37344eff/library/CMakeLists.txt#L249
> 
> https://github.com/brainboxdotcc/DPP/blob/788377d2b4fef949db3debd02d9acaea37344eff/library/CMakeLists.txt#L292
> 
> The warning flags can be definitely put in a variable (they can be probably set in `CMAKE_CXX_FLAGS` for every build type). Most of the other stuff however, could probably go completely or be replaced by more portable CMake constructs.

Please do not change this. We have to support windows msvc, and older msvc 2019 which won't work right if we try to let it auto deduce stuff. This is a case of 'if it aint broke dont fix it', lets not go overboard trying to change too much in one go, with this its best to do baby steps and do one or two changes at a time. Massive changes to cmakelists never ever go well. Right now, vcpkg is still broken from the last patch...

**Comment by braindigitalis** [comment]
> > > i dont agree with trying to deduce the c++ version.
> > 
> > 
> > I never used that one on my projects either. But I am still in favor of letting CMake automatically set the correct compiler flags, while telling it which standard to use, i.e. `target_compile_features(... cxx_std_17)` or `target_compile_featuers(... cxx_std_20)`. That's already done in the CMakeLists.txt, but for some reason we still set `-std=c++17` explicitly:
> > https://github.com/brainboxdotcc/DPP/blob/788377d2b4fef949db3debd02d9acaea37344eff/library/CMakeLists.txt#L179
> > 
> > https://github.com/brainboxdotcc/DPP/blob/788377d2b4fef949db3debd02d9acaea37344eff/library/CMakeLists.txt#L249
> > 
> > https://github.com/brainboxdotcc/DPP/blob/788377d2b4fef949db3debd02d9acaea37344eff/library/CMakeLists.txt#L292
> > 
> > The warning flags can be definitely put in a variable (they can be probably set in `CMAKE_CXX_FLAGS` for every build type). Most of the other stuff however, could probably go completely or be replaced by more portable CMake constructs.
> 
> Please do not change this (the -std). We have to support windows msvc, and older msvc 2019 which won't work right if we try to let it auto deduce stuff. This is a case of 'if it aint broke dont fix it', lets not go overboard trying to change too much in one go, with this its best to do baby steps and do one or two changes at a time. Massive changes to cmakelists never ever go well. Right now, vcpkg is still broken from the last patch...

looks like we might already be on the same page here, right? i misread i think...

**Comment by NexAdn** [comment]
> looks like we might already be on the same page here, right? i misread i think...

I think so. Again, I don't want to use the various compile features, but just the ones that explicitly state the required C++ standard (i.e. `cxx_std_17` and `cxx_std_20`). CMake should then be able to take care of selecting the right compiler option to tell the compiler which version to use. Specifying this correctly (i.e. setting them PUBLIC or INTERFACE) would also allow the exported CMake module to tell consumers of this library which C++ standard is required to compile against this library.

For the C++20 Coroutines support, this is already done in the current CMakeLists.txt (see my links above) and I suspect us manually setting `-std=c++17` in `CMAKE_CXX_FLAGS` has become redundant anyway.
