### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [brainboxdotcc/DPP#597]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [discord_voice_client](https://github.com/brainboxdotcc/DPP/blob/3ea77753f1d5d07110f4230d0471c8174ceb89fb/src/dpp/discordvoiceclient.cpp#L340 "Destructor for discord_voice_client")
- [role](https://github.com/brainboxdotcc/DPP/blob/ab47438ebc6a1d24cc3b95e08fde4dcc7998d9de/src/dpp/role.cpp#L46 "Destructor for role")
- [webhook](https://github.com/brainboxdotcc/DPP/blob/dc2ca1b6db210d3f8af8961113498db10f1bc14c/src/dpp/webhook.cpp#L53 "Destructor for webhook")

**Comment by braindigitalis** [comment]
thanks for the report, i'd welcome a PR for these.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by braindigitalis** [comment]
we looked at this before, clang-tidy is extremely aggressive on changing things how we don't want them to be, and clang-format was a total pain in the ass. any systems that offer suggestions should do them in line with the coding style guidelines over at dpp.dev.

**Comment by elfring** [comment]
:thought_balloon: Do you prefer any other development tools for removing redundant pointer checks (in more convenient ways)?
