### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [brainboxdotcc/DPP#598]
:thought_balloon: Would you like to [wrap any pointer data members](https://github.com/brainboxdotcc/DPP/blob/d4b74dae5a3fd7d2f7e9f458c90c16c4fc4fa588/src/dpp/discordclient.cpp#L78 "Update candidate: discord_client class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by braindigitalis** [comment]
no thanks, this will add extra complication to the library, and the library itself tracks the ownership of the pointers (and owns all pointers).
In fact we barely use any manual allocation via new at all, except in caches and a couple of internal values.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [apply C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "R.11: Avoid calling new and delete explicitly") for any more software components?

**Comment by elfring** [comment]
>In fact we barely use any manual allocation via new at all, …

:thought_balloon: How does such a feedback fit to improvable source code places?

Example:
https://github.com/brainboxdotcc/DPP/blob/d4b74dae5a3fd7d2f7e9f458c90c16c4fc4fa588/src/dpp/discordclient.cpp#L103

**Comment by braindigitalis** [comment]
> > In fact we barely use any manual allocation via new at all, …
> 
> 💭 How does such a feedback fit to improvable source code places?
> 
> Example:
> 
> https://github.com/brainboxdotcc/DPP/blob/d4b74dae5a3fd7d2f7e9f458c90c16c4fc4fa588/src/dpp/discordclient.cpp#L103

there really is no need for this to be a smart pointer, it is just added complexity. Its lifetime is managed by its owning class.

**Comment by elfring** [comment]
:thought_balloon: Are smart pointers provided for the avoidance of undesirable software behaviour?

:eyes: Where do you see owning objects for the pointers “etf” and “zlib”?

**Comment by elfring** [comment]
>This is the only place they are instantiated.

I know.

I interpret the linked source code in the way that the two pointer member variables “etf” and “zlib” are not initialised with “`nullptr`” so far.
Thus such a pointer combination is generally problematic in case an exception like “`std::bad_alloc`” would be thrown.

**Comment by elfring** [comment]
:eyes: Would you like to take another look at [the advice “Item 10:  Prevent resource leaks in constructors.”](https://ptgmedia.pearsoncmg.com/imprint_downloads/informit/aw/meyerscddemo/DEMO/MEC/MI10_FR.HTM "Description in the book “More Effective C++” by Scott Meyers")?

**Comment by braindigitalis** [comment]
changing everything to smart pointers is a potentially lazy option, the correct fix is shown here without needing to add complexity to the library.

https://github.com/brainboxdotcc/DPP/commit/3981360a3f5f4480eb8fd3beda0dba39fb7e62a4

We simply need to ensure that nullptr is set for those two values, and rethrow the std::bad_alloc after any cleanup. This is a much simpler change than refactoring an entire stable library (where a bad_alloc on construction of a discordclient has never happened in production in a real world system to our knowledge) to use unique_ptr.
