### ISSUE TITLE
Can't remove a member's nickname and roles with guild_edit_member

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#604]
**Git commit reference**
`d5f49c3fe22d1d14cadc1500f67fa9bdcffebca0`

**Describe the bug**
When using `cluster::guild_edit_member` to remove the nickname or roles of a member, it doesn't remove them. No error thrown. 

**To Reproduce**
e.g. this code:
```c++
auto m = dpp::find_guild_member(825407338755653642, 189759562910400512);
m.nickname = "";
m.roles = {};
bot.guild_edit_member(m);
```

**Expected behavior**
To remove the roles and nickname

**System Details:**
 - OS: Ubuntu
 - Discord Client used for testing [desktop]

**the fix**
The way the build_json method is made, the nickname and roles fields won't be send to discord when they're empty.

**Comment by flankytingz** [comment]
Changing
```c++
if (!this->nickname.empty())
  j["nick"] = this->nickname;
if (!this->roles.empty()) {
  j["roles"] = {};
  for (auto & role : roles) {
    j["roles"].push_back(std::to_string(role));
  }
}
```
to
```c++
j["nick"] = this->nickname;
j["roles"] = {};
for (auto & role : roles)
  j["roles"].push_back(std::to_string(role));
```
in `guild.cpp` should fix the issue.
