### ISSUE TITLE
VC connect without perms

### ISSUE THREAD

**Issue by rube200** [brainboxdotcc/DPP#608]
**Git commit reference**
`44fa00618ba6ea264fa27277a5031b432f7a76c9`

**Describe the bug**
When I request the bot to connect  (`guild->connect_member_voice`) to a voice channel that I know it doesn't have permission to, I don't get any kind of feedback about success because the function returns true.

**To Reproduce**
1. Create a voice channel and exclude the bot from connecting to it.
2. Call method to bot join the channel.

**Possible fixes**
Opt1. Make `guild->connect_member_voice` return false if it dont have permission.
Opt2. Expose some function to check if bot have permission to connect.
Opt3. Some kinda of callback to notify about the failure.

**Comment by braindigitalis** [comment]
the status value of connect_member_voice does not indicate a failure to join, it returns false if the guild member you pass to it is not on a voice channel.
To check permissions you must use the `channel::get_user_permissions()` function. The library does not do these sorts of things for you as it is a lightweight library and will not try and second guess what you are trying to do.
