### ISSUE TITLE
Fix sodium_LIBRARY not being assigned when null

### ISSUE THREAD

**Issue by rube200** [brainboxdotcc/DPP#611]
I am working with this lib for a bot, currently im using two cmake env, one is in my raspberry witch take a long time to compile for the first time and the second is a WSL(Debian), the problem is after setting everything up `cmake` wouldn't work throwing me this message ```CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
sodium_LIBRARY_RELEASE (ADVANCED)```

Original log:
![image](https://user-images.githubusercontent.com/20555316/218363542-abe4e4eb-6cfc-4d84-806a-754de9712f0b.png)

Log after some debug and mod code:
![image](https://user-images.githubusercontent.com/20555316/218363682-492b5e1f-b979-47b4-98c7-b1f790bed5dc.png)

Debug code:
![image](https://user-images.githubusercontent.com/20555316/218363758-5413fcae-aaa8-4679-80e4-0398968aaaf8.png)

**Comment by braindigitalis** [comment]
you need to read the output more closely, pkgconfig is missing, required by sodium

**Comment by braindigitalis** [comment]
yeah this fix is wrong. it says could not find sodium then enables voice support anyway, this would fail to compile or fail to link to a program

**Comment by rube200** [comment]
So i installed php since it was missing and also pkg-config and all got okay but
when i uninstall pkg-config again now this time gave me a diff output:
![image](https://user-images.githubusercontent.com/20555316/218414703-9b7558fa-b636-48a6-94c5-5ac5746c2473.png)
shouldn't it not enable voice if sodium depends of pkg-config??

Also sodium is installed but it didnt automatically install pkg-config:
![image](https://user-images.githubusercontent.com/20555316/218415484-e857beb0-fe97-4845-993e-a8e08e36f031.png)

**Comment by rube200** [comment]
also after uninstalling php and pkg-config back to "original setup of packages"
![image](https://user-images.githubusercontent.com/20555316/218416684-ed27745d-93b5-4f16-9ec5-ecb99c8f4ea8.png)

**Comment by NexAdn** [comment]
> So i installed php since it was missing and also pkg-config and all got okay but when i uninstall pkg-config again now this time gave me a diff output:

Looks to me like CMake just cached the details how to find sodium, so it's not surprising that it still considers it found after pkg-config is uninstalled. That's probably just CMake caching magic, not an issue with the CMakeLists.txt

**Comment by braindigitalis** [comment]
it is a bug that nowhere does it say pkgconfig is a dependency but this should be reported to sodium really. I think they consider cmake support a second class citizen in that neck of the woods ...

**Comment by braindigitalis** [comment]
the correct check is to check for pkgconfig in our own code before including findsodium.cmake. this will silently fail and disable voice support if pkgconfig is missing.
![image](https://user-images.githubusercontent.com/1556794/219954756-c53e7287-92c0-469a-969b-42daa0bebdd4.png)
