### ISSUE TITLE
Voice marker functionality: invalid pointer dereferencing

### ISSUE THREAD

**Issue by KontraCity** [brainboxdotcc/DPP#621]
**Git commit reference**
9131e84d5236ca3308b45ebc4b8af84faf2c0bdb

**Describe the bug**
On `aarch64` function `dpp::discord_voice_client::write_ready()` checks voice marker incorrectly:
Line 788 `discordvoiceclient.cpp`: `if (outbuf[0].packet.size() == 2 && ((uint16_t)(*(outbuf[0].packet.data()))) == AUDIO_TRACK_MARKER) {`
Assuming `outbuf[0].packet` is `{0xFF, 0xFF}`, `outbuf[0].packet.data()` returns `char*` pointer to first item, it is dereferenced and overflowed, returning `-1`. After that `char` is converted to `uint16_t` and `-1` is compared to `0xFFFF`, which is always `false`.
Compiler is also giving warning:
`/home/kontracity/Libraries/DPP/src/dpp/discordvoiceclient.cpp: In member function ‘void dpp::discord_voice_client::write_ready()’:
/home/kontracity/Libraries/DPP/src/dpp/discordvoiceclient.cpp:788:81: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  788 |    if (outbuf[0].packet.size() == 2 && ((uint16_t)(*(outbuf[0].packet.data()))) == AUDIO_TRACK_MARKER) {`
The same warning is produced at line 1109:
`/home/kontracity/Libraries/DPP/src/dpp/discordvoiceclient.cpp: In member function ‘dpp::discord_voice_client& dpp::discord_voice_client::skip_to_next_marker()’:
/home/kontracity/Libraries/DPP/src/dpp/discordvoiceclient.cpp:1109:116: warning: comparison is always true due to limited range of data type [-Wtype-limits]
 1109 |  while (!outbuf.empty() && outbuf[0].packet.size() != sizeof(uint16_t) && ((uint16_t)(*(outbuf[0].packet.data()))) != AUDIO_TRACK_MARKER) {`

**To Reproduce**
For some reason bug occurs only on `aarch64`.
1. Register audio marker lambda callback with `dpp::cluster::on_voice_track_marker()`
2. Send some audio data with `dpp::discord_voice_client::send_audio_opus()`
3. Send audio marker with `dpp::discord_voice_client::insert_marker()`
4. Observe that callback is not called.

**Expected behavior**
Audio marker callback should be called when audio marker is hit.

**Suggested fix**
Assuming `outbuf[0].packet` is `{0xFF, 0xFF}`,
If we change `((uint16_t)(*(outbuf[0].packet.data())))` to `(*((uint16_t*)(outbuf[0].packet.data())))`:
1. `outbuf[0].packet.data()` returns `char*` pointer to first item
2. `char*` pointer is converted to `uint16_t*` pointer. **Now it captures second byte of** `outbuf[0].packet`.
3. `uint16_t*` pointer is dereferenced properly.
4. `0xFFFF` is compared to `0xFFFF`. It is true -> voice marker is hit.
5. Callback function is now called properly.
This solution is tested both on `aarch64` and `x64` systems.

**System Details:**
 - OS (`uname`): `Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux`
 - Desktop Discord client is used for testing.

**Comment by braindigitalis** [comment]
thanks for the report!

**Comment by braindigitalis** [comment]
fixed and on master branch, thanks again!
