### ISSUE TITLE
Cannot find "nlohmann/json_fwd.hpp" when used as a dependency to project

### ISSUE THREAD

**Issue by xugro** [brainboxdotcc/DPP#624]
**Git commit reference**
393a1a69af6a87eda6613f1efd7a83c6c6c042bb

**Describe the bug**
Can not compile it says :
```
/DPP/library/../include/dpp/snowflake.h:23:10: fatal error: nlohmann/json_fwd.hpp: No such file or directory
   23 | #include <nlohmann/json_fwd.hpp>
```

**System Details:**
 - OS: Ubuntu 22.04.1 LTS

**Additional context**
Problem fixed by changing **CMAKE_SOURCE_DIR** to **CMAKE_CURRENT_SOURCE_DIR** on [CMakeLists.txt](https://github.com/brainboxdotcc/DPP/blob/master/CMakeLists.txt) line:97

**Comment by MCausc78** [comment]
do you have installed [json library](https://github.com/nlohmann/json)?

**Comment by xugro** [comment]
I wanted to use the bundled one.

**Comment by braindigitalis** [comment]
this feature is new. I'll make the change suggested to use CMAKE_CURRENT_SOURCE_DIR
