### ISSUE TITLE
Error build dpp

### ISSUE THREAD

**Issue by Maksim990** [brainboxdotcc/DPP#625]
**Git commit link**
fatal: detected dubious ownership in repository at '/home/kotik9821/DPP'

**Describe the error**
Delivered both globally and locally, looked at the forums does not help

/usr/bin/ld: /tmp/ccpP31Tu.o: in "main" function:
index.cpp:(.text+0x2a7): undefined reference to "dpp::cluster::cluster(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const& , unsigned int, unsigned int, unsigned int, unsigned int, bool, dpp::cache_policy_t, unsigned int, unsigned int)"
/usr/bin/ld: index.cpp:(.text+0x2d8): undefined reference to "dpp::cluster::~cluster()"
collect2: error: ld exited with return code 1

**Play**
Steps to reproduce behavior:
1. Create a file index.cpp
```c++
#include <dpp/dpp.h>
#include <iostream>
#include <fstream>

using namespace std;

int main() {
    dpp::cluster bot("");
	 
	bot.on_log(dpp::utility::cout_logger());

	bot.on_slashcommand([](const dpp::slashcommand_t& event) {
	     if (event.command.get_command_name() == "ping") {
	        event.reply("Pong!");
	    }
	});
	bot.on_ready([&bot](const dpp::ready_t& event) {
	    if (dpp::run_once<struct register_bot_commands>()) {
	        bot.global_command_create(
	            dpp::slashcommand("ping", "Ping pong!", bot.me.id)
	        );
	    }
	});

	bot.start(dpp::st_wait);
}
```
2. Run the command `g++ -static index.cpp -o kotiktest`

**Expected behavior**
Code build

**System Information:**
ArchLinux system, using Discord Desktop

**Screenshots**
![изображение](https://user-images.githubusercontent.com/66716255/221792880-574e2bfc-44ba-4bcd-a587-f0dc507cdf60.png)

**Comment by NexAdn** [comment]
> fatal: detected dubious ownership in repository at '/home/kotik9821/DPP'

This one's a problem local to you. Please make sure the ownership of files in your repo is corret, i.e. make sure you are the owner of _all_ files in that directory: `sudo chown -R $(whoami):$(whoami) /home/kotik9821/DPP`.

> /usr/bin/ld: index.cpp:(.text+0x2d8): undefined reference to "dpp::cluster::~cluster()"

This one means a problem linker. Compare this with your build command:

> `g++ -static index.cpp -o kotiktest`

Apparently you don't link against DPP and thus the linker can't find the symbols. This can probably be solved by a simple `-ldpp`.

**Comment by Maksim990** [comment]
![изображение](https://user-images.githubusercontent.com/66716255/221807504-b137d206-1e3c-4091-a011-c2272242056c.png)
```
/usr/bin/ld: cannot be found -ldpp: No such file or directory
collect2: error: ld completed with return 1
```

**Comment by NexAdn** [comment]
Do you have DPP installed properly on your system? I recommend installing [dpp from AUR](https://aur.archlinux.org/packages/dpp). This ensures you have DPP in your standard libary search path. Otherwise the linker is unable to find libdpp.so.

**Comment by NexAdn** [comment]
This might have to do with the `-static` flag. It enables static linking and DPP is distributed as a shared library. I think there is an option to enable building a static library, but it's probably not enabled by default. If you drop the `-static` flag, everything should work.

**Comment by Maksim990** [comment]
However, I never climbed into the build parameters, so I don’t understand anything there yet.

**Comment by braindigitalis** [comment]
there is no .a built as standard for dpp to link it statically. It is not something we have tested. Please link without the -static, see dpp.dev for documentation.

**Comment by Maksim990** [comment]
Thanks, it worked. And will it be possible to somehow add the possibility of a complete assembly using `-static`?
