### ISSUE TITLE
Shouldn't description_localizations be ignored?

### ISSUE THREAD

**Issue by rube200** [brainboxdotcc/DPP#628]
I was working around commands in context menu and found that description is ignored but description_localizations is not, shouldn't it be?

Description being ignored:
https://github.com/brainboxdotcc/DPP/blob/25006668103d0e77252b45b3098ff457a8422189/src/dpp/slashcommand.cpp#L203-L205

Description Localizations being parsed without checking type
https://github.com/brainboxdotcc/DPP/blob/25006668103d0e77252b45b3098ff457a8422189/src/dpp/slashcommand.cpp#L222-L227

**Comment by rube200** [comment]
Also slashcommand doesn't have add_localization without description parameter.
https://github.com/brainboxdotcc/DPP/blob/cca04b83ca8c1945300595f2849e4f5b92d242c5/include/dpp/appcommand.h#L1084

**Comment by Commandserver** [comment]
Changed in the master branch. Thanks for the report @rube200

**Comment by Commandserver** [comment]
> Also slashcommand doesn't have add_localization without description parameter.
> 
> https://github.com/brainboxdotcc/DPP/blob/cca04b83ca8c1945300595f2849e4f5b92d242c5/include/dpp/appcommand.h#L1084

this is also changed in master :D
