### ISSUE TITLE
Reply async?

### ISSUE THREAD

**Issue by hanss0n** [brainboxdotcc/DPP#654]
**Is your feature request related to a problem? Please describe.**

Would it be possibly to implement some kind of asynchronous reply functionality?
I'm using a language model to generate responses based on command parameters, but it's not fast enough to generate a reply within the 3 second window, so I either have to create a new message entirely or use the thinking method somehow?

**Describe the solution you'd like**
A reply async function that allows the bot to think and then posts a reply once the message is ready.

**Describe alternatives you've considered**
I can probably implement this myself somehow, but it'd be a nice feature nonetheless, though maybe it's easier than I think?

**Comment by Axyte** [comment]
About all library functions exposed are already async unless you opt to explicitly use `_sync` ones.

In this case, you need to use the `thinking()` function yes, or a placeholder message for `reply()` and later edit it when your response is ready.

**Comment by hanss0n** [comment]
Thanks a lot for the quick response!
