### ISSUE TITLE
Cluster cannot be closed gracefully.

### ISSUE THREAD

**Issue by iSLC** [brainboxdotcc/DPP#66]
**Describe the bug**
Destroying `dpp::cluster` blocks "indefinitely" (_quotes explained bellow_).

**To Reproduce**
1. `std::unique_ptr< dpp::cluster > c = std::make_unique< dpp::cluster >("token...");`
2. `c->start(true);`
3. Later on: `c.reset();`

**Expected behavior**
Expecting code `c.reset();` to return so execution can continue.

**System Details:**
 - OS: [e.g. Windows 10 x64]
 - Discord Client used for testing [mobile, desktop, web]

**Additional context**
The `dpp::cluster` destructor gets stuck. From the looks of it it seems to happen in the `dpp::request_queue` actually. `in_thread->join();` waits indefinitely. Probably because `while (!terminating) {` is never reached again after the initial entry.

`while (recv(notifier, &n` is also blocking if no data is received (_why the quotes_). So you need to receive data to enter the loop in case you want to move the `!terminating` check inside the inner loop as an alternative. Thus, preventing the thread from actually terminating.

**Comment by braindigitalis** [comment]
Thanks, i'll need to use a select on that while()/recv() or similar, to make it bail out.
I'll look into this.

**Comment by braindigitalis** [comment]
fixed in dev/master

**Comment by iSLC** [comment]
> fixed in dev/master

Was a little confused this morning when I read that because I was looking at commits and only saw the test case. Later when I got home I saw that the changes were actually in the 61a86be19a2f198f801046bf37e5da25dc1d468d commit.

I just tried it and can confirm it behaves as expected now. Ty.
