### ISSUE TITLE
400 bad request when trying to ban a member

### ISSUE THREAD

**Issue by Linker-123** [brainboxdotcc/DPP#69]
**Describe the bug**
400 bad request error when trying to ban a guild member.

**To Reproduce**
1. `bot.guild_ban_add(guild_id, user_id, 0, "reason doesn't matter", <callback>)`
2. In the callback log the error message

**Expected behavior**
A successful request.

**Screenshots**
None

**System Details:**
 - Arch Linux
 - Discord Client used for testing web

**Additional context**
None

**Comment by braindigitalis** [comment]
thanks for reporting, I'll try and repro and fix for you later!

**Comment by Linker-123** [comment]
The errors vector is empty I can only extract the `message` field form the get_error method.

**Comment by braindigitalis** [comment]
this should be resolved now, thanks for the report!
