### ISSUE TITLE
Bad handling of optional parameters in slash commands by the unified command handler

### ISSUE THREAD

**Issue by The-personified-devil** [brainboxdotcc/DPP#71]
When getting a parameter from an interaction event, if it isn't found, a reference to a default-constructed static variant is returned.
When being default-constructed, a variant holds a default-constructed instance of the first alternative.
This results in there being no clear indication whether the command was provided, since the variant just holds an empty string.

I suggest to prepend std::monostate to the alternatives of command_value, as to have a clear state for optional commands.

Directly related to this, the check to see if the parameter was optional in the routing for slash commands in the unified command handler checks for the variant being valueless by exception, even though that isn't the state if the parameter wasn't provided.

Though that is kinda caught by the exception handling around the following type switch, though this breaks when the type of the optional parameter is a string and is also hacky.

The proposed suggestion would also fix those issues.

Also, the integer branch of the type switch is missing a break :)

**Comment by braindigitalis** [comment]
resolved in latest set of pushes, thanks for the suggestion!
