### ISSUE TITLE
Build Failure with MinGW on Windows using vcpkg due to Misuse of target_compile_definitions() 

### ISSUE THREAD

**Issue by Sightem** [brainboxdotcc/DPP#710]
**Git commit reference**
`28d390cb52c019badd4111c208af47ccb6c15225`

**Describe the bug**
Misuse of `target_compile_definitions()` in CMakeLists.txt for adding compiler flags. This misuse causes a build failure when building on Windows with MinGW, as the command expects preprocessor macros but receives compiler flags instead.

**To Reproduce**
1. Attempt to build the library on Windows using MinGW. [The relevant CMakeLists.txt](https://github.com/brainboxdotcc/DPP/blob/master/library-vcpkg/CMakeLists.txt) file uses `target_compile_definitions()` to add compiler flags.
2. Observe the build failure, with error messages indicating "macro names must be identifiers".

**Expected behavior**
The build process should complete without errors. Compiler flags should be added with `target_compile_options()` instead of `target_compile_definitions()`.

**System Details:**
- OS: 
-  Compiler: MinGW, GCC
-  Build system: CMake

**Additional context**
The problematic CMake code appears to be [here](https://github.com/brainboxdotcc/DPP/blob/28d390cb52c019badd4111c208af47ccb6c15225/library-vcpkg/CMakeLists.txt#L14):

```cmake
target_compile_definitions(
	"${LIB_NAME}" PUBLIC
	"DPP_BUILD"
	"$<$<PLATFORM_ID:Windows>:$<$<CONFIG:Debug>:/sdl;/std:c++17;/Od;/DEBUG;/sdl;/MP;/DFD_SETSIZE=1024;/Zc:preprocessor>>"
	"$<$<PLATFORM_ID:Windows>:$<$<CONFIG:Release>:/std:c++17;/O2;/Oi;/Oy;/GL;/Gy;/sdl;/MP;/DFD_SETSIZE=1024;/Zc:preprocessor>>"
)
```

These lines try to add compiler flags (such as /sdl, /std:c++17, etc.) using `target_compile_definitions()`, which is (as far as I can understand) meant for preprocessor macros, not compiler flags. As a result, the build process fails with error messages about "macro names must be identifiers".

**Comment by braindigitalis** [comment]
vcpkg with mingw is not supported.
please use msvc with mingw. we are not able to support every weird combination of compiler everyone throws at it. if you really want to use gcc, use wsl2, and use gcc in its native environment instead of trying to shoehorn it into windows.

**Comment by Mishura4** [comment]
issue was reintroduced by https://github.com/brainboxdotcc/DPP/pull/745

**Comment by Mishura4** [comment]
Fixed again by https://github.com/brainboxdotcc/DPP/pull/844
