### ISSUE TITLE
Can't get DM channel. (get_dm_channel)

### ISSUE THREAD

**Issue by LayaCube** [brainboxdotcc/DPP#719]
Hello, I'm sorry if this is quite stupid.

```cpp
bot->get_dm_channel(msg->author.id);
```
This line always returns zero, even if the channel exists, even if the user exists.
I've also tried the following:
```cpp
bot->get_dm_channel(dpp::snowflake(msg->author.id));
```

The documentation does not seem to provide an exemple, and I was not able to understand the problem myself. 

Thank you for reading.

**Comment by Andosius** [comment]
Hey,

I am new to DPP but I found some promising functions, maybe that helps?
https://github.com/brainboxdotcc/DPP/blob/0c77102c6b7b0c4d9fe04f2dd90a591f9d694bc0/src/dpp/cluster/dm.cpp#L25
Especially L33?

Usually its faster to ask via Discord: https://discord.gg/dpp


GL =)

**Comment by braindigitalis** [comment]
in dpp you don't create DM channels yourself, and a DM doesn't have a dpp::channel 

use direct_message_create member of the cluster object, using the user id you want to message.

nothing else is required as DM are received by message_create (check it's a DM via the is_dm method of the message) and bots cannot join group DMs.
