### ISSUE TITLE
how to send a message to a channel without an event

### ISSUE THREAD

**Issue by big2shane** [brainboxdotcc/DPP#721]
Hi,

I'm planning to use this library but I cant find any examples on sending a message to a specific channel without an event?
Something like this: https://stackoverflow.com/a/51120299

Any help would be appreciated.

**Comment by MCausc78** [comment]
https://dpp.dev/classdpp_1_1cluster.html#aa6ae3dc32ebc2dd14264962710d35af7. And please in future ask such questions in our Discord server: https://discord.gg/dpp
