### ISSUE TITLE
OpenBSD Fails to build D++ due to broken <locale> system header 

### ISSUE THREAD

**Issue by mrtuxa** [brainboxdotcc/DPP#765]
i cant compile DPP

i get this error

```
In file included from /home/mrtuxa/pkgs/DPP/src/dpp/discordevents.cpp:25:
In file included from /usr/include/c++/v1/iostream:38:
In file included from /usr/include/c++/v1/istream:163:
In file included from /usr/include/c++/v1/ostream:140:
In file included from /usr/include/c++/v1/locale:218:
/usr/include/c++/v1/__bsd_locale_fallbacks.h:122:17: error: use of undeclared identifier 'vasprintf'; did you mean 'vsprintf'?
    int __res = vasprintf(__s, __format, __va);
                ^
/usr/include/c++/v1/cstdio:124:9: note: 'vsprintf' declared here
using ::vsprintf _LIBCPP_USING_IF_EXISTS;
        ^
In file included from /home/mrtuxa/pkgs/DPP/src/dpp/discordevents.cpp:25:
In file included from /usr/include/c++/v1/iostream:38:
In file included from /usr/include/c++/v1/istream:163:
In file included from /usr/include/c++/v1/ostream:140:
In file included from /usr/include/c++/v1/locale:218:
/usr/include/c++/v1/__bsd_locale_fallbacks.h:122:27: error: cannot initialize a parameter of type 'char *' with an lvalue of type 'char **'
    int __res = vasprintf(__s, __format, __va);
                          ^~~
/usr/include/stdio.h:269:21: note: passing argument to parameter here
int      vsprintf(char *, const char *, __va_list);
                        ^
[ 71%] Building CXX object library/CMakeFiles/dpp.dir/__/src/dpp/discordclient.cpp.o
2 errors generated.
*** Error 1 in target 'library/CMakeFiles/dpp.dir/__/src/dpp/discordevents.cpp.o'
*** Error 1 in . (library/CMakeFiles/dpp.dir/build.make:538 'library/CMakeFiles/dpp.dir/__/src/dpp/discordevents.cpp.o': cd /home/mrtuxa/pkg...)
*** Error 2 in . (CMakeFiles/Makefile2:102 'library/CMakeFiles/dpp.dir/all')
*** Error 2 in /home/mrtuxa/pkgs/DPP/build (Makefile:156 'all': /usr/bin/make -s -f CMakeFiles/Makefile2 all)
```

**Comment by mrtuxa** [comment]
the package names of the dependencies are the same as in FreeBSD btw

**Comment by braindigitalis** [comment]
this error is not in dpp, it looks like your standard libraries are broken?

**Comment by braindigitalis** [comment]
definitely something sus with openbsd here: 

https://www.google.com/search?q=%2Fusr%2Finclude%2Fc%2B%2B%2Fv1%2F__bsd_locale_fallbacks.h%3A122%3A17%3A+error%3A+use+of+undeclared+identifier+%27vasprintf%27%3B+did+you+mean+%27vsprintf%27%3F%0A++++int+__res+%3D+vasprintf%28__s%2C+__format%2C+__va%29%3B

**Comment by braindigitalis** [comment]
this is a [bug in the headers in openbsd](https://github.com/gbdev/rgbds/issues/1111) and [not something we can fix](https://marc.info/?l=openbsd-bugs&m=157758838031146&w=2) as far as I can tell. have you tried updating openbsd?

The issue has been around for many years and affects many projects. C++ just doesn't seem well tested there.

if you do find a workaround that doesn't break other systems a PR would be welcomed. I don't have access to an openbsd system to test this.

**Comment by mrtuxa** [comment]
i updated my system but still the same error

**Comment by Jaskowicz1** [comment]
I'm now investigating this.

**Comment by Jaskowicz1** [comment]
This issue still persists as of the latest version of [OpenBSD (install73.iso, amd64)](https://www.openbsd.org/faq/faq4.html#Download).

**Comment by Jaskowicz1** [comment]
I've got a fix, i'm testing it and ensuring that everything works. Will launch a PR soon.

**Comment by Jaskowicz1** [comment]
I've launched a PR to fix this https://github.com/brainboxdotcc/DPP/pull/880 :)
