### ISSUE TITLE
`discord_voice_client::send_audio(...)` doesn't use given input data when called with already encoded data

### ISSUE THREAD

**Issue by The-personified-devil** [brainboxdotcc/DPP#82]
`discord_voice_client::send_audio(...)` doesn't actually use the given audio data when telling it the input data is already encoded. It just sends the buffer that the data encoded from raw pcm input data would be placed into.

**Comment by braindigitalis** [comment]
send_audio is not supposed to work with already encoded data. What is your intended use case, and what are you trying to do?

**Comment by braindigitalis** [comment]
having a quick look at this there's an option that it looks like I didn't finish implementing:

```
	 * @param use_opus Some containers such as .ogg may contain OPUS
	 * encoded data already. In this case, we don't need to encode the
	 * frames using opus here. We can set use_opus to false and bypass the
	 * codec, only applying libsodium to the stream.
```
hence the "it doesnt do this" :)
I'd welcome a PR to make it work, otherwise i'll take a look when i have time to do so.

**Comment by braindigitalis** [comment]
I've put a preliminary fix in place for this, but i'd be interested to receive some sample code that duplicates the issue, so i can test my fix. Can you please provide some simple test code or a link to a github for me to duplicate the issue?

**Comment by braindigitalis** [comment]
as you've tested this in your bot (but it didn't suit your requirement anyway due to fixed frame size) is this now closeable?
thanks!
