### ISSUE TITLE
Unit test tidyup

### ISSUE THREAD

**Issue by braindigitalis** [brainboxdotcc/DPP#936]
test.cpp and friends are large and unwieldy. it is now over 2000 lines, this is 🤢 - as a small project this could do with tidying up and breaking down into smaller files. anything under the unittest folder will be linked into one executable.

This is an ideal first issue for an intermediate developer wanting to contribute to D++.

**Comment by braindigitalis** [comment]
#948 introduced crases and caused unit tests to fail:

```
coro: offline job                                            FAIL
coro: offline coroutine                                      FAIL
coro: offline task                                           FAIL
coro: offline async                                          FAIL
coro: online event handler                                   PASS
coro: online api calls                                       PASS
coro: online mumbo jumbo in event handler                    SKIPPED

Execution finished in 55.809 seconds.
Failed: 4 Passed: 138 Skipped: 19 Percentage: 97.18%
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)
```

As such this breaks CI so we had to roll it back. Anyone welcome to try again but we must make sure that it doesnt break the tests.

**Comment by Jaskowicz1** [comment]
This is still open if anyone wants to take this!

**Comment by Jaskowicz1** [comment]
Gonna take this on myself. I will be basing it off #948 as we agreed that the format was good.

**Comment by Jaskowicz1** [comment]
I'd put this off for a bit as I faced issues with Mac and whatnot, will look to maybe pick this up over Christmas if no-one else does (as I am busy until then).

**Comment by Jaskowicz1** [comment]
Reminder, we're looking for people to complete this project! I'll post this in the Discord too!

**Comment by mayankag32** [comment]
Hello @Jaskowicz1, I would like to work on this issue, is it still open?

**Comment by braindigitalis** [comment]
sure feel free to grab it, please do not add any external dependencies such as catch2!

**Comment by Jaskowicz1** [comment]
Going to actually take this on myself this time.

**Comment by Mishura4** [comment]
Bump
