### ISSUE TITLE
D++ does not support setting images (e.g) banner through guild_edit

### ISSUE THREAD

**Issue by Mishura4** [brainboxdotcc/DPP#957]
It seems the [Modify Guild](https://discord.com/developers/docs/resources/guild#modify-guild) endpoint supports setting images, for example the guild banner, through the guild object. This requires sending the image data encoded as Base64 in the `banner` field.

[cluster::guild_edit](https://dpp.dev/classdpp_1_1cluster.html#a54e2174822bb1796a541f849d568664c) takes a dpp::guild as a parameter. However its image fields, for example [banner](https://dpp.dev/classdpp_1_1guild.html#ad5736b31cf35641cb2c78f9353d3a8a5) are a [utility::iconhash](https://dpp.dev/structdpp_1_1utility_1_1iconhash.html), which do not support base64 strings as they are a pair of integers.

Supporting this will require refactoring those fields as well as how retrieving the image URLs work.

**Comment by Jaskowicz1** [comment]
I'll fix this :)

**Comment by braindigitalis** [comment]
please don't change how we store the banner. iconhash is the most efficient storage for it. instead please provide a method for uploading a guild banner without adding variables to the class which will make it bigger and be empty 99.999% of the time

**Comment by Jaskowicz1** [comment]
> please don't change how we store the banner. iconhash is the most efficient storage for it. instead please provide a method for uploading a guild banner without adding variables to the class which will make it bigger and be empty 99.999% of the time

The idea isn't to change how it's stored, but I do need to discuss how to tackle some of the issues on discord.

**Comment by Neko-Life** [comment]
add a new method to set banner with base64 string. `set_banner_base64` that accept string param, possibly with some util to read image file as base64 `readfile_base64` for convenience

**Comment by Jaskowicz1** [comment]
> > please don't change how we store the banner. iconhash is the most efficient storage for it. instead please provide a method for uploading a guild banner without adding variables to the class which will make it bigger and be empty 99.999% of the time
> 
> My idea isn't to change how it's stored, but I do need to discuss how to tackle some of the issues on discord.

i lied

**Comment by Jaskowicz1** [comment]
I've decided i'm not gonna take the issue :)
